### ISSUE TITLE
New Bounties not counted in summary box, not shown in Bounties tab

### ISSUE THREAD

**Issue by jespow** [bountysource/core#1001]
Also, the team and its bounties are not searchable.  That has already been reported:  https://github.com/bountysource/core/issues/962

Maybe the issues are related?

see:  https://www.bountysource.com/teams/rocketchat

![image](https://cloud.githubusercontent.com/assets/1042860/12533211/82f7c4c6-c1dd-11e5-99e2-f87e14d7032a.png)

![image](https://cloud.githubusercontent.com/assets/1042860/12533215/9a6de900-c1dd-11e5-972c-d5081bf55f28.png)

**Comment by engelgabriel** [comment]
This is a big problem indeed!

**Comment by hjchan** [comment]
Just to clarify, "Issues" tab inside team will show all the issues of the team as well as the issues that have bounties, you can filter and search in the tab. Whereas "Bounties" tab show the bounties post by the team.
