### ISSUE TITLE
Tracker has already been taken

### ISSUE THREAD

**Issue by Mailaender** [bountysource/core#1009]
There seems to be no way to un-take a tracker. I want to move OpenRA/ra2 to @orabot.

![image](https://cloud.githubusercontent.com/assets/756669/13728731/c88539ea-e921-11e5-885e-022427086afe.png)

You also never answered the e-Mail I sent to support@bountysource.com on 21.02.2016 22:47.

**Comment by JedMeister** [comment]
:+1: Same issue here... :cry:

**Comment by ChristophWurst** [comment]
any update? Is there a way to fix this (as user)?

**Comment by Mailaender** [comment]
Guess you will have to put a bounty on this issue for @bountysource to react. ;)

**Comment by ChristophWurst** [comment]
Seriously? Still unresolved?

Still can't put any bounty in my issue tracker and now you start to take 10% of it due to inactivity. Wow.

**Comment by ChristophWurst** [comment]
Okay, to be precise I still can put bounties on issue of my bug tracker but nobody will take notice because no labels are added and the title is not updated accordingly.

**Comment by ChristophWurst** [comment]
Hey @NoNonsense126,

thanks for fixing. When can we expect the patch on bountysource.com?

**Comment by NoNonsense126** [comment]
Hey @ChristophWurst,

I believe it should be working now. Perhaps you can try it out at https://www.bountysource.com/tools 

Let me know if you have any problems with it!

**Comment by ChristophWurst** [comment]
Thank you, @NoNonsense126. It worked for us. We could finally re-install the github tool for our issue tracker!

**Comment by tgiphil** [comment]
I have the same problem with:

![image](https://user-images.githubusercontent.com/124747/74337924-1864b200-4d56-11ea-9590-f0f3d7389d18.png)

https://github.com/mosa/MOSA-Project

Can anyone help?
