### ISSUE TITLE
Can't associate my GitHub issue-tracker with my team.

### ISSUE THREAD

**Issue by andreas-jonsson** [bountysource/core#1017]
I can't associate my GitHub issue-tracker with my Bountysource team.

If I sign-in and select Tools from the dropdown menu my project is not listed.

Team: https://www.bountysource.com/teams/gopherc
Repo: https://github.com/gopherc/gopherc

(I'm the project-owner and I'm listed as an Public member on GitHub.)

**Comment by SecUpwN** [comment]
Had the same problem with our [AIMSICD](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector) project. Make sure to grant your team repo access to bountsource in `Thirsd-party access`. Then try again to sign in and the link should update automatically.

**Comment by andreas-jonsson** [comment]
Thanks! That solved the problem.

**Comment by kathyqian** [comment]
@andreas-jonsson How did you get Bountysource to request access? I'm not seeing any pending requests for my organization, though it seems to work fine with my personal repos.
