### ISSUE TITLE
Issue titles do not get updated with new bounties

### ISSUE THREAD

**Issue by SecUpwN** [bountysource/core#1018]
Good evening @bountysource, our [Android IMSI-Catcher Detector](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector) project is currently experiencing a strange bug: When a new bounty has been placed on a certain Issue, the title of the GitHub Issue does not get changed. We recently had a $100 bounty and nobody even noticed it. Awful! I've tripple-checked, all necessary permissions should be granted to bountysource. Please help me investigating this Issue.

**Comment by x-a-n-a-x** [comment]
I confirm this bug. 

There was a $25 bounty on this issue: https://github.com/OpenRA/OpenRA/issues/9206 until someone increased the bounty up to $40 but the title of the issue didn't change. :-/

I had to rename the title by myself. Please fix this bug, it's really annoying to know that developers can't be informed of new bounty updates.

**Comment by SecUpwN** [comment]
@rappo, would you please help us here? This is really important for us right now.

**Comment by Aokromes** [comment]
I think this issue appears when big amount of issues exists, we have the same problem on https://github.com/TrinityCore/TrinityCore/issues

**Comment by hjchan** [comment]
#1011
