### ISSUE TITLE
Bounty search should not show paid out bounties

### ISSUE THREAD

**Issue by rappo** [bountysource/core#1025]
Kind of obvious, but it doesn't do that yet. Perhaps a "include paid out" checkbox?

Suggested via support@.

**Comment by kaizensoze** [comment]
Didn't realize bountysource was open source. Would've submitted an issue/pull request instead of a support ticket. Do developers searching for bounties even care about what's been paid out? It'd kinda be like having a "Show already rented" checkbox on an apartment rental site, no?

**Comment by rappo** [comment]
@kaizensoze I don't think it's crucial to have paid out bounties, but it's nice for users to see all of the "success stories" (though, this could be handled elsewhere).

**Comment by hjchan** [comment]
Bountysearch didn't show paid out bounties now and the closed issues are able to filter out.
