### ISSUE TITLE
CLA signer

### ISSUE THREAD

**Issue by fommil** [bountysource/core#1039]
instead of having the CONTRIBUTING page that nobody reads, I can heartily recommend  https://cla-assistant.io/

and while we're on the topic of hooks, https://lgtm.co is a game changer.

**Comment by rappo** [comment]
I setup CLA assistant. I used pi-hole's text as the example text. Hopefully it's all setup correctly. Definitely open to feedback or review.

**Comment by fommil** [comment]
LGTM is no longer needed, ever since github added support for this directly :-)
