### ISSUE TITLE
How can I set the expiration for a bounty I've just created?

### ISSUE THREAD

**Issue by dandv** [bountysource/core#1045]
I've just created [my first bounty](https://github.com/linuxmint/Cinnamon/issues/3883#issuecomment-243874387) and didn't set an expiration date. How can I add one?

**Comment by rappo** [comment]
You can't add an expiration after posting, but you can always email support@bountysource.com to have the bounty refunded to your Bountysource account (assuming work isn't in-progress). Our policy is to refund no-questions-asked, if there's no dev activity.
