### ISSUE TITLE
Restore from Trash doesn't work

### ISSUE THREAD

**Issue by svobodajiri** [bountysource/core#1047]
Latest OS version with latest updates (2016-09-10)

Right-click on picture in Picture folder -> Move to Trash

Open Trash, right-click on picture -> Restore from Trash

Windows just closes with nothing restored. The same when I click on Restore All

All that works is Cut the picture from Trash and Put back into Picture folder.

**Comment by rappo** [comment]
@svobodajiri Not sure what project you're trying to report this for, but this is unrelated to Bountysource.
