### ISSUE TITLE
Bountysource.com cannot be archived at archive.org or archive.is websites.

### ISSUE THREAD

**Issue by 3rdwiki** [bountysource/core#1050]
Logging the webpages is impossible in archive.org or archive.is

Here is a bounysource Core bug logged at archive.is:

https://www.bountysource.com/issues/1384853-add-support-for-gnu-savannah
http://archive.is/aLodY
https://web.archive.org/web/*/https://www.bountysource.com/issues/1384853-add-support-for-gnu-savannah

As you can clearly see this does not bode well for transparency of the financials.
As there is no paper-trail and you cannot keep track of how people/programs  are doing.

Look forward to seeing bountysource Inc. clear this up as it represents a certain amount of trust at the bottom.

**Comment by nicolas17** [comment]
All websites using Angular or other client-side rendering will have the same problem...

**Comment by rappo** [comment]
This is problem with archive.org, not us. We have no problems being archived -- in fact we'd embrace it. They need to adapt to sites like ours that use Angular. Petition them to add the changes they need to archive our site.

**Comment by volth** [comment]
it looks fixed http://archive.is/85n11
