### ISSUE TITLE
[feature] offers from developers to develop a feature

### ISSUE THREAD

**Issue by epoberezkin** [bountysource/core#1058]
The bounty shows how much money is raised. It would be good if developers could submit a "proposed" amount that they'd like to receive to implement the requirement (like fundraising target in kickstarter).

**Comment by juanj** [comment]
I don't know if is what you are looking for but developers can say that the bounty is to low and set a bounty goal

![screen shot 2016-11-17 at 11 46 21 pm](https://cloud.githubusercontent.com/assets/1958175/20418931/1584a88a-ad20-11e6-9437-8556492ac0af.png)
