### ISSUE TITLE
Display some recent or popular bounties in search page 

### ISSUE THREAD

**Issue by harishreddy-m** [bountysource/core#1063]
The current search page doesn't display any bounties.Shows a white page next to search criteria sidebar.

Display some popular bounties in that space.

When I tried to search by language, I tried with javascript and java....white page still remains.
At least display "No bounties found" message.

**Comment by hipyhop** [comment]
Or better yet, it could actually search the bounties and show the actual results.

**Comment by kaiansaari** [comment]
Closing this issue as the search functionality has been restored and includes a default search
