### ISSUE TITLE
Find Missing Numbers

### ISSUE THREAD

**Issue by KevinZhong111** [bountysource/core#1064]
Hello everyone! 

I am trying to write code in python to find missing numbers in a text file. For example, I have a text file containing many characters, including integers between 1 and 20, except for 11. How are you going to find the missing number 11? 

This is the text file: 
[text_file.txt](https://github.com/bountysource/core/files/587022/text_file.txt)

This is my python code (doesn't work):
[search.txt](https://github.com/bountysource/core/files/587027/search.txt)

You either fix my code, or show me yours. I expect comments please.

Thanks!

**Comment by iamprakashom** [comment]
I am on it.
