### ISSUE TITLE
Search page/api (?) is broken

### ISSUE THREAD

**Issue by Oele** [bountysource/core#1065]
The search page on https://www.bountysource.com/bounties/search is broken. 

Whatever the query, the API call to https://api.bountysource.com/search/bounty_search always replies with: 

/**/ CORS({"data":{"error":"Method not found"},"meta":{"status":404,"success":false,"pagination":null}})

No error is shown to the end user.

**Comment by hexagon6** [comment]
Can confirm this.

Search page is just empty, no matter what parametere

In console I see: 

| msg | file |
| ------------- |:-------------:|
|  access token still valid    | app-f6f0c628cba2d0836f650ab5424d0a8f.js:21:19096 | 
|  API Error                   |  angular.min.js:89:231 | 
|  Request GET             | "https://api.bountysource.com/search/bounty_search"angular.min.js:89:231 | 
| Request Params Object { direction: "desc", order: "bounty_total", languages: "", trackers: "", per_page: 50, page: 1, access_token: "...", callback: "CORS" } |  | 
.... followed by many other similar messages

Authenticated via github, using Firefox.

**Comment by kholbekj** [comment]
+1

**Comment by GabrielTK** [comment]
+1

**Comment by GabrielTK** [comment]
Someone should set this to critical

**Comment by sahilsharma011** [comment]
👍

**Comment by dewyatt** [comment]
@wkonkel @rappo Bountysource search page has been broken for a long time.

**Comment by snaiperskaya96** [comment]
Have to confirm that 2 months later the search function (and all the stuff that rely on api.bountysource.com) is broken because of CORS. This is making the website almost unusable

**Comment by hexagon6** [comment]
Who can fix this?

**Comment by snaiperskaya96** [comment]
The bountysource team I guess

**Comment by hexagon6** [comment]
I would like to volunteer to fix this, but I don't understand yet why it is broken. Any clues @wkonkel @rappo ?

**Comment by snaiperskaya96** [comment]
Just search for "API search" in the issues tab, it's explained  there

**Comment by snaiperskaya96** [comment]
#1012

**Comment by rappo** [comment]
dupe of https://github.com/bountysource/core/issues/1012
