### ISSUE TITLE
issue not updated when bounty added

### ISSUE THREAD

**Issue by simonmichael** [bountysource/core#1067]
https://www.bountysource.com/issues/5973215-postings-with-just-a-balance-assertion-but-no-amount-should-work shows the $10 bounty I just added, but the corresponding https://github.com/simonmichael/hledger/issues/157 was not updated by Bountysource (which normally works in this repo). I wonder if it's due to applying [this workaround](https://github.com/simonmichael/hledger/issues/427#issuecomment-261811857) for https://github.com/bountysource/core/issues/1062.

**Comment by wetneb** [comment]
I have the same problem: GitHub is out of sync with bountysource.
https://github.com/OpenRefine/OpenRefine/issues/805 indicates a $265 bounty
https://www.bountysource.com/issues/985941-implement-wikidata-reconciliation-was-freebase indicates a $300 bounty.

**Comment by rappo** [comment]
GitHub plugin functionality has been restored, this shouldn't be an issue anymore.
