### ISSUE TITLE
Accessing bountysource.com/teams/bountysource redirects

### ISSUE THREAD

**Issue by OmgImAlexis** [bountysource/core#1070]
If you try to navigate to https://bountysource.com/teams/bountysource it automatically redirects to the salt page where there's no links back to any of the tabs such as issues.

**Comment by 3rdwiki** [comment]
Here's that Link to the issues for you:
(although as Salt is completely unaccountable in any way - I think rappo planned it that way)

https://www.bountysource.com/teams/bountysource/issues
