### ISSUE TITLE
Bounty search never returns results

### ISSUE THREAD

**Issue by SaffronSnail** [bountysource/core#1071]
Whenever I attempt to search for bounties the search page is blank. I have tried extremely broad search parameters (for example, the only restriction being c++) and still receive no results. Everything else about the website appears to be working fine.

I am on arch linux running Google Chrome 54.0.2840.100. I also run into this problem when I try it with Opera 42.0.2393.94-1.

**Comment by o01eg** [comment]
I tried too and it looks like api return ```/**/ CORS({"data":{"error":"Internal server error."},"meta":{"status":500,"success":false,"pagination":null}})``` error.

**Comment by pangelo** [comment]
I can also confirm this issue on Firefox 45.5.1 on Debian testing, both when logged in or not.

**Comment by cyberinferno** [comment]
+1

**Comment by skarpushin** [comment]
So... is Bountysource platform alive? Search is still not working. I've also sent an email to the support couple days ago and still no response.

**Comment by Sceat** [comment]
+1

**Comment by rappo** [comment]
closing, dupe of https://github.com/bountysource/core/issues/1012
