### ISSUE TITLE
Clarify language about $5 minimum on checkout page

### ISSUE THREAD

**Issue by superquest** [bountysource/core#1073]
![image](https://cloud.githubusercontent.com/assets/4335621/21748960/ef953f00-d5cd-11e6-99b8-954c44a9d58f.png)

As I made my first donation in a few months, it was unclear whether the $5 minimum donation was per-project or across all projects. I had to look up the documentation in this repo, which has better language: [" ... if you contribute $1/month to a project ..."](https://github.com/bountysource/core/wiki/Salt-Frequently-Asked-Questions#is-there-a-minimum-contribution)

This really tripped my up ... here I am filing issues instead of writing checks!!!

Thanks

**Comment by rappo** [comment]
Happy to accept PRs from anyone who has better language for this. A nice easy issue to get people contributing... :)

**Comment by kaiansaari** [comment]
@hjchan one for you please.
