### ISSUE TITLE
Cannot add github account

### ISSUE THREAD

**Issue by moeiscool** [bountysource/core#1074]
I tried emailing, twitter, and facebook. Please help me link my github account to my bountysource account. It says it's already linked when I go to link it but when I check in account it says there is no link to any github account. In my github account it shows bountysource as an accepted app.
I removed it and tried again with the same result.

**Comment by rappo** [comment]
@moeiscool It says your GitHub account is linked here:
https://www.bountysource.com/people/35301

did you already resolve the problem? feel free to close this issue if so.

**Comment by moeiscool** [comment]
I will not be using bountysource anymore, thanks for trying
