### ISSUE TITLE
Is Boutysource still alive?

### ISSUE THREAD

**Issue by PhrozenByte** [bountysource/core#1077]
I'm wondering whether Bountysource as a project is still alive or presumably dead.

Major issues like #1023, which virtually make creating new teams impossible, didn't receive any fixing attempt for nine months, and one neither gets a response on IRC, nor via support email for a week. I really would ❤️ to use Bountysource for my open-source project, it's an amazing concept I wasn't aware of since recently, it would be a great pity if we loose Bountysource.

**Comment by saroff** [comment]
About important issues - bounty search also broken: https://github.com/bountysource/core/issues/1076

**Comment by 3rdwiki** [comment]
As long as I can 'donate bitcoin' to a bug, and the bounty show up on a page that I can reference in mailing lists - which bountysource presently does - then _yes_ Bountysource is still alive.

**Comment by rappo** [comment]
Bountysource is not dead, but we've definitely slowed to a crawl. I've written up a few tasks that we could use help on and posted bounties from the Bountysource Salt coffers. If you want to help, take a look at some of those new issues. Feel free to send us useful PRs, or throw some $ behind our campaign here: https://salt.bountysource.com/teams/bountysource
