### ISSUE TITLE
Add "Send via Coinbase" button to admin/cash_outs/pending

### ISSUE THREAD

**Issue by rappo** [bountysource/core#1080]
If cash out method is BTC, add a button to that specific cash out request that sends the payment via Coinbase. This could be batched if desired.

- Successful transaction should trigger the "Mark as Sent" action in the Admin
- (bonus) Add transaction ID/details to the "Mark as Sent" email

**Comment by rappo** [comment]
@barkovv Just a heads-up that this issue is under consideration for removal, based on https://github.com/bountysource/core/issues/1086

**Comment by frnco** [comment]
@rappo Considering the Coinbase issues mentioned in #1086, I think before creating the button you should decide if you'll keep Coinbase or consider possible Coinbase alternatives. If considering alternatives, maybe this should be postponed until a final decision on which payment processor will be used.

**Comment by rappo** [comment]
Just to be clear, it's now safe to continue with development on this issue.

@barkovv, have you had any luck tackling this? @frnco has made progress on developer onboarding, check his PR: https://github.com/bountysource/core/pull/1094

**Comment by barkovv** [comment]
@rappo 
I can't get current thing working. /admin/people simply doesn't show any people (however I've created them).

**Comment by rappo** [comment]
It should list people... what do you see when you go to /admin/people/ID?

**Comment by barkovv** [comment]
@rappo @frnco 
It "loads" forever either on /admin/people or /admin/people/ID

According to DevTools I've get this response for GET /people :
```
/**/ CORS({"data":null,"meta":{"status":200,"success":true,"pagination":null}})
```

There is a strange query from ActiveRecord (v. 4.0.13) in log:
```
    Person Exists
    First exec was: SELECT  1 AS one FROM "people"  WHERE ("people"."email" = 'test@test.com' AND "people"."id" != 1) LIMIT 1
```
This returns 0 rows, but if I manually query the same but with people.id = 1  it returns 1 row. Is it bug or something else? It seems that I setup all things fine but admins stuff is not working.
![1](https://cloud.githubusercontent.com/assets/5094065/24061309/fa167b54-0b67-11e7-87bc-f0638c77359e.png)
![2](https://cloud.githubusercontent.com/assets/5094065/24061273/d117c79e-0b67-11e7-9cbe-f7de0d079f28.png)
[gem_versions.txt](https://github.com/bountysource/core/files/851668/gem_versions.txt)
[log.txt](https://github.com/bountysource/core/files/851697/log.txt)

**Comment by frnco** [comment]
Returning 0 rows seems like a problem with contions. Check the where and the includes for that page.

**Comment by rappo** [comment]
bounty increased: https://www.bountysource.com/issues/42707610-add-send-via-coinbase-button-to-admin-cash_outs-pending

**Comment by johanlives** [comment]
Coinbase account disabled long ago. Closing.

**Comment by painor** [comment]
so is there currently no way to cashout with bitcoin unless we contact the support ?
