### ISSUE TITLE
Core Project Developer Onboarding, First TIme Local Install and Contribution Guidelines

### ISSUE THREAD

**Issue by frnco** [bountysource/core#1082]
Setting up a local copy is, currently, not straight-forward, and I am having quite some trouble, so I figured it's a good opportunity to help documenting stuff.

I know maintaining is a lot of work and it's hard to answer everyone, so I will keep trying, but any info you guys can give me (Dependencies, gotchas, Environment setup etc.) will help a lot.

**Comment by juanj** [comment]
I manage to get it running with docker.
First you need a Postgres running. You can use `docker run --name postgres -d postgres`
Then you need to create the bountysource docker image. In the core folder run `docker build -t bountysource .`
Bountysource uses a lot of ENV variables. I found it easy to create a copy of .env.test, edit it and pass it to docker.
After that you can configure the DB with `docker run --env-file envfile bountysource rake db:setup`
And run it with `docker run -p 3000:3000 --env-file envfile bountysource rails server`

Two important ENV vars to set are `BOUNTYSOURCE_API_URL` and `DATABASE_URL`

**Comment by barkovv** [comment]
@juanj did you managed to give youself "money" for "cashout" in local instanse?

**Comment by rappo** [comment]
@juanj thank you for helping others get setup. If anyone out there has the time to write up clear guides for new developers, that would be amazing! We'll try to help out where we can -- we're slowly starting to carve out more time for Bountysource these days.

@barkovv did you get the admin working? You can gift money to yourself from admin/people/(ID)/financial
![image](https://cloud.githubusercontent.com/assets/2245234/23735996/28403186-043e-11e7-84ba-87e3c9082675.png)

**Comment by frnco** [comment]
@rappo I am writing an onboarding guide, covered the basic setup already, with site running.

I am currently working on instructions for setting up some data for the new devs to play with, do you have any suggestions on that?

First idea that came to mind is providing a pre-populated database, minus sensitive data. Then also providing one-liners to create user, admin user etc. Should be enough to work on most of the site.

**Comment by barkovv** [comment]
@frnco Did you get working adding a user and browsing admins data? Could you share your experience?

**Comment by frnco** [comment]
@barkovv Browsing data is currently a problem as I did not create a dataset yet, especially since I am mostly focusing on fixing the search.

I'll try to get to it asap, but if anyone can help with a starting dataset it'd be awesome.

As for the admin, for some reason Rails Console always returns that Person Exists when I try creating a User through it, so I created a user through the web interface and turned it into an admin account through the console using

    Person.find(INSERT_PERSON_ID_HERE).update_attribute(:admin, true)

Then I could log in using `/admin`, just remember you may have to check the environment variable for the admin secret.

**Comment by barkovv** [comment]
@frnco I've created account via web interface and gave it admins rights via postgresql console. Then I login into /admin but it's empty. When I did it first time /admin worked fine but for some reason I couldn't reproduce this state. For example in /admin/people tab nothing is listed despite of correct data in database. So I asked you that question. Did you do some additional steps to get /admin functional working?

**Comment by barkovv** [comment]
It sees that rails uses wrong bountysource API in my case.
```
POST /admin/login 200 OK Api::V0::HomeController#login JSON 8.8 (DB 0.8, View 0.1) {"email"=>"test@test.com", "password"=>"[FILTERED]", "admin_secret"=>"[FILTERED]", "per_page"=>250, "callback"=>"CORS", "vendor_string"=>"bountysource", "home"=>{"email"=>"test@test.com", "password"=>"[FILTERED]", "admin_secret"=>"[FILTERED]", "per_page"=>250, "callback"=>"CORS"}} {}
```
There figures **Api::V0::HomeController**.

Can I specify correct API (v2 I guess) via irb console or with something else? Any help is appreciated.

**Comment by frnco** [comment]
@barkovv, from what I understand from `config/routes.rb` admin functions actually use API `v0`.

As for having no data, I didn't find any mock/example data do populate the db, so I plan to create a dataset to be used when developing, but I didn't get to it yet.

Maybe @rappo or @wkonkel have something that can be used, maybe just it's a partial dataset, be it a sql script, seeds file or whatever...?

**Comment by frnco** [comment]
#1094 closes this.

**Comment by JARWATI** [comment]
Pada tanggal 6 Mar 2017 14.56, "Fernando Cordeiro" <notifications@github.com>
menulis:

Setting up a local copy is, currently, not straight-forward, and I am
having quite some trouble, so I figured it's a good opportunity to help
documenting stuff.

I know maintaining is a lot of work and it's hard to answer everyone, so I
will keep trying, but any info you guys can give me (Dependencies, gotchas,
Environment setup etc.) will help a lot.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bountysource/core/issues/1082>, or mute the thread

**Comment by JARWATI** [comment]
div,
        p,
        a,
        li,
        td {
            -webkit-text-size-adjust: none;
            -ms-text-size-adjust: none;
        }

        body {
            margin: 0;
            padding: 0;
        }

        table td {
            border-collapse: collapse;
            border: 0px;
        }

        .ExternalClass {
            width: 100%;
        }

        .ExternalClass * {
            line-height: 100%
        }

        .preheader {
            display: none !important;
            visibility: hidden;
            opacity: 0;
            color: transparent;
            height: 0;
            width: 0;
        }

        a[x-apple-data-detectors] {
            color: inherit !important;
        }

        div[style*="margin: 16px 0"] {
            margin: 0 !important;
        }
        /* Opacity Hover effect */

        td:hover[id=hover] {
            -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=80)";
            filter: alpha(opacity=80);
            -moz-opacity: 0.8;
            -khtml-opacity: 0.8;
            opacity: 0.8;
            -webkit-transition: opacity .3s ease;
            -moz-transition: opacity .3s ease;
            -o-transition: opacity .3s ease;
            transition: opacity .3s ease;
        }

        .appleLinks a {
            color: #ffffff;
            text-decoration: none;
        }

        .backbutton img:hover {
            -webkit-animation-name: thumb;
            -webkit-animation-duration: 200ms;
            -webkit-transform-origin: 50% 50%;
            -webkit-animation-iteration-count: 2;
            -webkit-animation-timing-function: linear;
        }

        input {
            display: none;
        }

        @media only screen and (min-device-width: 320px) and (max-device-width: 1024px) {
            a[href^="tel"],
            a[href^="sms"],
            a {
                color: inherit !important;
                cursor: default !important;
                text-decoration: none !important;
            }
        }

        @media only screen and (max-width: 580px) {
            *[class=fluid] {
                width: 100% !important;
                height: auto !important;
                display: table !important;
            }
            *[class=hide] {
                display: none !important;
                width: 0px !important;
            }
            *[class=app-icon] {
                width: 90px !important;
                height: auto !important;
            }
            *[class=padding-bottom] {
                padding-bottom: 25px !important;
            }
            *[class].show {
                display: block !important;
                overflow: visible !important;
                float: none !important;
                width: 100%;
                height: auto !important;
                max-height: none !important;
            }
            *[class=w320] {
                width: 320px !important;
                height: auto !important;
            }
            *[class=w290] {
                width: 290px !important;
                height: auto !important;
            }
            *[class=w261] {
                width: 261px !important;
                height: auto !important;
            }
            *[class=w145] {
                width: 145px !important;
                height: auto !important;
            }
            *[class=w90] {
                width: 90px !important;
                height: auto !important;
            }
            *[class=w15] {
                width: 15px !important;
                height: auto !important;
            }
            *[class=w8] {
                width: 8px !important;
                height: auto !important;
            }
            *[class=w9] {
                width: 9px !important;
                height: auto !important;
            }
            *[class=intro-pad] {
                padding-left: 6px !important;
                padding-right: 6px !important;
            }
            *[class=footer-copy] {
                font-size: 12px !important;
                line-height: 15px !important;
            }
        }
    
    
    



    
    
        
            
                
                    
                        
                            
                                
                                
                                    
                                        
                                            
                                                Hi there!
                                                
                                                JARWATI is playing Bubble Witch 3 Saga and has invited you to play.
                                                Start playing now.
                                            
                                        
                                    
                                
                                
                                    
                                        
                                            
                                            
                                        
                                    
                                
                                
                                    
                                        
                                        
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                    
                                                                
                                                            
                                                        
                                                        
                                                        
                                                            
                                                                
                                                                    
                                                                        Bubble Witch 3 Saga
                                                                    
                                                                
                                                            
                                                            
                                                                
                                                                    
                                                                        KING
                                                                    
                                                                
                                                            
                                                            
                                                                
                                                                    
                                                                        Help Stella the good witch defeat evil in this new bubble game!
                                                                    
                                                                
                                                            
                                                            
                                                                
                                                                    
                                                                        
                                                                            
                                                                                
                                                                                    Play Now!
                                                                                
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                        
                                        
                                    
                                
                                
                                    
                                        
                                            
                                            
                                        
                                    
                                
                                
                                    
                                        
                                        
                                            
                                                © King­.­com Limited 2016. All rights reserved.
