### ISSUE TITLE
[STOP CASHOUT FRAUD] BTC Cash out from a team should be restricted to "Verified" teams

### ISSUE THREAD

**Issue by rappo** [bountysource/core#1088]
EDIT: Leaving the original text, but this issue is now for:
BTC Cash out should be restricted to "Verified" teams, https://github.com/bountysource/core/issues/1088#issuecomment-287415457
---

In a (almost completely unsuccessful) attempt to launder money from stolen/hacked Paypal accounts, we have people who:

1. create a Bountysource account
2. create a team
3. use stolen Paypal accounts to fund a team
4. request a cash out (via BTC)

See https://github.com/bountysource/core/issues/1086#issuecomment-285819853 for details.

We need to come up with a solution that's both low effort and effective. I'll throw out a few suggestions to start, but open to ideas.

### Teams Must be "Verified"

In order to submit a cash out from a team balance, the team must be "verified". This introduces a manual check by staff that the team is legit.

A nice little "Verified" checkmark might also increase people's willingness to donate.

### User must be "verified" to use BTC cashouts

Same idea as team verification, but limited to users and exclusively for BTC cashouts.

### Accept fraud as a fact, make it easier to undo

Add an admin button that can mark a team/person as a fraudster and undo all of their transactions, delete teams/accounts, etc. This still requires us to go into Paypal and manually refund transactions.

### Create a waiting period before cashing out

Most offending accounts are ~1 day old. If they had to wait 60 days this might deter them.

Annoys new users who just earned money.
Probably ineffective if the fraudsters are patient.

### Stop supporting BTC

As discussed in #1086. Pretty sure we don't want this :)

**Comment by frnco** [comment]
Some ideas from https://www.paypal.com/us/webapps/mpp/security/prevent-fraudulent-orders

Contacting customer. Can be a great idea if Paypal account was stolen, but trivial to circumvent if it is a fake PayPal account with a stolen card, i.e. by using fake anonymous mail and burner phone. But if age of Phone, Paypal Account or Email Account can be verified it could be a great start.

Waiting period ("Delayed Shipment" section, PayPal suggests 24-48hours, I'd probably go with more than that). This one is almost perfect, except googling told me on my first result that Credit Card Chargebacks on Fraud suspicion can be made 120 days after the charge, possibly even more.

This one also presents a possibility, IMHO the best one: https://www.paypal.com/us/webapps/mpp/security/credit-card-fraud

Specifically asking for Photo ID.

As seen here, on the "Sample Response":
https://developer.paypal.com/docs/api/payments/#payment_get

`funding_instrument` has some info including 4 last Credit Card Digits, plus first and last name as present on Credit Card. This info needs to be legit as the bank wouldn't approve a charge to a fake Credit Card. That makes it possible to ask for a picture of the Credit Card, and/or some form of ID.

From this early research, nothing's 100% safe, but it seems it's possible to get pretty close to that.

**Comment by o01eg** [comment]
To restrict fraud what if allow to cash out only money which was get by completing issues?

**Comment by frnco** [comment]
@o01eg Create Team, Create Dev, Post Issue as Team, Start Issue as Dev, Close Issue as Dev, Claim Bounty as Dev, Accept Claim as Team....

Harder, but still not nearly enough imho...

**Comment by Riiume** [comment]
Just posted a [small bounty](https://www.bountysource.com/issues/42911055-how-do-we-stop-paypal-btc-fraud) for this issue, I invite others to kick in if they have the disposable resources.

**Comment by rappo** [comment]
@Riiume thank you for getting the bounty pot going!

After thinking about this a bit more during the week, I've decided that the best solution is that Teams must be "verified" in order to have the option to cash out a team balance to BTC. As soon as we have an developer who's willing to take on this issue I'm happy to sit down and design it with them.

I still consider this issue urgent and urge anyone who is willing and able to contribute to the bounty.

**Comment by rappo** [comment]
Alternatively, requiring tax forms for any BTC cashout could be enough to stop fraud anyway... and we already want to automate that process (https://github.com/bountysource/core/issues/1078)

**Comment by frnco** [comment]
I'm considering tackling this after we get search and dev onboarding up.

From my earlier comment and the decision to have verifies teams, is there some "verification" process already or do we need to set this up from scratch?

IMHO we need some form of ID, preferrably tied to a payment from PayPal using a Credit Card. Tax forms are an option but it may vary a lot depending on countries, i.e. in Brazil we don't need to pay taxes until a certain threshold, and even after you do need to pay everything's done electronically.

Anyways, what do you guys think?

**Comment by rappo** [comment]
We have a "team claim" process, but it's hacky and manual. We don't currently have any "verification" process that officially asserts a person is a team member or that the bountysource team is sanctioned by the corresponding project.

As an American company we:
1. are required to collect tax forms when a $600 yearly threshold is met
2. are required to collect tax forms from *anyone*, citizen or not (w9, w8, w8-ben)

Requiring Paypal or CC as ID would be challenging for a number of reasons, but most importantly because the reason many people use BTC in the first place is because they don't have access to  Paypal or a CC.

If we require the tax forms and/or a government ID for any persons requesting a cash out regardless of their yearly threshold, my belief is that it would drastically cut out fraud. Starting with a simple completed and e-signed PDF might be the best approach.

There are some ID verification services that may be worth looking into as well. If you've used Coinbase, they have a system where you hold up your ID to the camera (front and back) and then take a head shot. The ID is verified and then matched with your photo. I'm not sure who they use or how much it costs, but there are third party services out there for this.

**Comment by benepo** [comment]
Would this be preventing our recent bounties from posting?  [LSST](https://www.bountysource.com/teams/lsstepo) is a legitimate non-profit looking to use Bountysource for crowdsourcing key development tasks.  Like IBM, our bounties are larger in value than most others.  We had one successful bounty but the next two were approved by PayPal but don't appear in our Team dashboard or the Bountysource homepage.

**Comment by benepo** [comment]
Sigh.  Well, I've tried to contact a support person via email, IRC, the [CEO's phone number](http://www.buzzfile.com/business/Bountysource-Inc.-415-651-4799) (which auto-hangs up), Twitter, and GitHub.  At this point we are forced to assume the Bountysource service is not production ready and we'll look to other alternatives like [FreedomSponsors](https://freedomsponsors.org/).

P.S. Your old [bountyC](http://www.bountyc.com/) site is still active and should probably redirect to Bountysource at some point.

**Comment by rappo** [comment]
@benepo 

1. This would not prevent you from posting bounties. What gave you that impressive?
2. Patience is a virtue :). Feel free to use FreedomSponsors instead.
3. http://www.bountyc.com/ has no connection to us and this is the first I've heard of it. What makes you think it's directly related?

**Comment by benepo** [comment]
Hi @rappo

1. We submitted two Bountysource Posts and received the associated PayPal receipts but the payments weren't listed in our Activity screen nor the Bountysource homepage so there was no way to confirm the bounty was processed successfully or promote it.
2. We request customer support via multiple channels 5 business days ago.  I'm not sure how much patience you expect of new customers.
3. [Reference 1](https://en.wikipedia.org/wiki/Open-source_bounty#References) on the open-source bounty Wikipedia page references BountyC but the linked article then describes Bountysource.

**Comment by rappo** [comment]
@benepo 
1, Just took care of your issues in support. Let's keep this thread for the related topic. Feel free to follow up in support if there are more questions
2. We're volunteer run and work normal jobs, Bountysource takes a backseat to those priorities.
3. We've learned that Wikipedia is not a reliable source for anything :)

**Comment by c4pt000** [comment]
implement "netverify" into payments, (cash or not)


similar to major crypto exchanges might help alleviate problems of non-id matching payment(s) and  better protect payment systems, think binance., cex.io, coinbase,

**Comment by c4pt000** [comment]
KYC, AML, (know your customer) via ID, netverify supports ID verification based on ID info,.

**Comment by thecyberd3m0n** [comment]
Maybe stop supporting PayPal and support more cryptos.

Paypal fraud would be prevented
Cashouts would be immediate
You would provide great service and you can use Metamask or even gerenate keys on frontend using JS

**Comment by johanlives** [comment]
In the 

> So PayPal is the only option? :/ Do you support SEPA bank transfers? I don't have a PayPal account and will not have one, but already doing one bounty.

In the event of a significant bounty payout and no Paypal is available to the developer, we may organise a wire.  Please get in contact at support@bountysource.com to discuss
