### ISSUE TITLE
Fix bounty stat formatting of Teams

### ISSUE THREAD

**Issue by clearnote01** [bountysource/core#1090]
![ibm](https://cloud.githubusercontent.com/assets/9555129/23821906/177ca18e-0666-11e7-8ecf-89a66619ac6f.png)

See the bounty stats in the right box.

**Comment by rappo** [comment]
What browser are you using? Can't reproduce in Firefox 52.0 and Chrome 56.0.2924.87

**Comment by clearnote01** [comment]
Funny I am on Chromium Version 56.0.2924.87 (64-bit) as well, it shows like that for me. Firefox shows it fine without any issue (52.0)

**Comment by frnco** [comment]
Which OS?

**Comment by rappo** [comment]
closing... feel free to re-open with steps to reproduce.
