### ISSUE TITLE
Convert UI to React

### ISSUE THREAD

**Issue by corytheboyd** [bountysource/core#1092]
Angular is _soooo_ 2014, Bountysource needs to start using React and ES9.

**Comment by frnco** [comment]
Why not Vue?

Can do a Vue version, but it's a pretty big enterprise, we'd need either a lot more people or a lot more funding.

Plus I'd consider an Elixir rewrite for the back-end more interesting than a front-end rewrite, especially with the current scenario with the JS Frameworks...

**Comment by rappo** [comment]
@corytheboyd I thought you wanted us to be a purely mobile app, make up your mind! 😺
