### ISSUE TITLE
Bounties not showing up in multiple ways

### ISSUE THREAD

**Issue by bparker06** [bountysource/core#1098]
Trying to add bounties to existing github issues often yields a blank page:

https://www.bountysource.com/issues/41452425-cannot-join-netplay-rooms-on-linux?utm_campaign=plugin&utm_content=tracker%2F296058&utm_medium=issues&utm_source=github&show_profile_modal=1

Only if we create a brand new issue will it let us attach a bounty. But even then, not all bounties even show up, for example this page https://www.bountysource.com/teams/libretro/bounties is missing this bounty: https://www.bountysource.com/issues/43504135-cannot-join-netplay-rooms-on-linux

I have been talking with @rappo about this for the last week, but I wanted to make sure these issues were documented as I don't think a solution was ever found.

**Comment by VanillaNinjaD** [comment]
I recently had a developer recommend bountysource as a motivational tool. Shortly after that, I pledged to an open GitHub project issue and my money disappeared, I don't see it under my pledge history and it is not attached to the GitHub issue. I have sent an email to support@bountysource.com but have heard nothing back. Needless to say its frustrating at the least.

**Comment by hjchan** [comment]
I guess there is some misunderstanding about the bounties and the issue page.

https://www.bountysource.com/teams/libretro/bounties will show the bounties posted by this team whereas https://www.bountysource.com/teams/libretro/issues show the issues and bounties of those issues. Thus, not all bounties show up in bounties page, but it will show in issues page.

Hope this clarifies.
