### ISSUE TITLE
Bounty not promoted via Twitter

### ISSUE THREAD

**Issue by jpturcotte** [bountysource/core#1101]
Hello,
I created [this $20 bounty](https://www.bountysource.com/issues/37258870-tablet-incorrectly-detects-hovering-as-touching-on-macos) on April 4th, and paid an extra $20 to get it promoted. However, it has not been tweeted yet. I also emailed support on the 7th, without success. Can you help me, please? Thank you!

**Comment by VanillaNinjaD** [comment]
I recently had a developer recommend bountysource as a motivational tool. Shortly after that, I pledged to an open GitHub project issue and my money disappeared, I don't see it under my pledge history and it is not attached to the GitHub issue. I have sent an email to support@bountysource.com but have heard nothing back. Needless to say its frustrating at the least.

**Comment by dentarg** [comment]
Same thing happened to [our bounty](https://www.bountysource.com/issues/45000501-update-python-client-to-search-api-v3), paid $20 to get the tweet, but it didn't happened. Haven't contacted support (yet?) about it tho.

**Comment by jpturcotte** [comment]
Sent another message to support!

> Hello,
> I messaged you months ago about having paid $20 to get a bounty promoted on Twitter, and nothing ever happened. I have yet to receive an answer from you. I even opened an issue on GitHub (https://github.com/bountysource/core/issues/1101), and I am not alone. Now the bounty is almost completed, and I want a REFUND. Thank you! 
> Sincerely,
> Jean-Philippe Turcotte

**Comment by rappo** [comment]
I believe all support requests for this issue have been handled. If not, please send another email to support@bountysource.com and we'll get it taken care of.
