### ISSUE TITLE
Add support for Mantis

### ISSUE THREAD

**Issue by vboctor** [bountysource/core#1107]
#944 adds MantisBT support.  However, it has the following issues:

- Issue shows up as closed, even though it is not.
- Tracker shows up as "Unknown Tracker" - It should use the part of the page title after the `-`.
- Logo shows generic gray logo.
- The title has "- MantisBT" at the end which is the title of the bug tracker, rather than part of the issue title.

Happy to develop any necessary fixes on MantisBT itself to make this work.  Or configure this specific tracker in Bounty Source to show as a known tracker or both.

Here is an example:
- https://www.bountysource.com/issues/45646860-0022935-optimize-change-log-for-printing-mantisbt
- https://www.mantisbt.org/bugs/view.php?id=22935

**Comment by vboctor** [comment]
It seems that the existing code parses the MantisBT classic HTML (used by v1.x) instead of using the APIs.  The appropriate solution should do the following:

- Use REST API (enabled by default starting with MantisBT 2.8.0, available in previous releases but not enabled by default).
- Fallback to SOAP API for instances < 2.8.0.

**Comment by zoek1** [comment]
@vboctor, i suppose that the reference to use is  [mantishub/MantisPhpClient](https://github.com/mantishub/MantisPhpClient), right?

**Comment by vboctor** [comment]
@zoek1 The REST API is the present + future.  The SOAP API will give us backward compatibility for majority of MantisBT out there.

That is a PHP client that talks to MantisBT SOAP API.  So you can re-use from PHP or use as a reference if you need a ruby client.

The REST API should be easy.  A `GET` to `<base url>/api/rest/issues/<issue id>` would get you issue `12345` info in json format.  Since we are relying on anonymous access, no need for sending Authorization header.

In both cases, you will need to extract the issue id and instance base path from the given view issue URL.  For example, for url `https://www.mantisbt.org/bugs/view.php?id=22935`, the following would be calculated:

The following should be calculated:
Base Path: `https://www.mantisbt.org/bugs`
Issue ID: `22935`

Let me know if you any other questions.

**Comment by vboctor** [comment]
How is progress on this @zoek1 ?

**Comment by zoek1** [comment]
Great, I'm finishing the ruby client and working in the integration @vboctor.

**Comment by vboctor** [comment]
@zoek1 how is this work going?

**Comment by vboctor** [comment]
@zoek1 any progress on this?

**Comment by NoNonsenseSolutions** [comment]
@vboctor can the SOAP API's mc_issue_get be accessed without authentication?

**Comment by vboctor** [comment]
@NoNonsense126 Getting an issue should work without authentication in the case where anonymous access is enabled.  I think that would be the majority case for bounty scenario.

- For REST API - this means skipping the Authorization header when issuing a GET /api/rest/issues/1234
- For SOAP API - from what I recall you pass in a blank username and password.

We should lead with REST API and fallback to SOAP, since SOAP API will be removed in the next major release.
