### ISSUE TITLE
Unable to reconnect to websocket client when websocket gets closed. 

### ISSUE THREAD

**Issue by dhinesh-raja** [bountysource/core#1108]
I am using websocket4net to connect to the websocket. But when the connection gets disconnected it is not able to reconnect to the websocket once again. Below is the code which I have used

public static async Task webSocketConnect(String uri, String topicName)
            {
                log.Info("Entering to webSocketConnect method: " + Thread.CurrentThread.ManagedThreadId + " - " + topicName);
                await Task.Run(() =>
                {
                    var ws = new WebSocket(uri);
                    var retry = true;
    
                    ws.Opened += (sender, e) =>
                    {
                        retry = false;
                        log.Info("Websocket Connected for: " + topicName);
    
                    };
    
                    ws.MessageReceived += async (sender, e) =>
                    {
                        retry = false;
                        log.Error(e.Message);
    
                    };
    
                    ws.Error += async (sender, e) =>
                    {
                        log.Error("Error occured: " + topicName + "\n");
                        log.Info(e.Exception + "\n");
                        retry = true;
                        ws = new WebSocket(uri);
                        while (retry)
                        {
                            if (!(ws.State.ToString().Equals("Open")) && !(ws.State.ToString().Equals("Connecting")))
                            {``
                                ws.Open();
                                await Task.Delay(2000);
                            }
    
                        }
                    };
                    ws.Closed += async (sender, e) =>
                              {
    
                                  log.Info("Websocket getting closed for the following topic : " + topicName + "\n");
                                  log.Info(e + "\n");
                                  retry = true;
                                   ws = new WebSocket(uri);
                                   while (retry)
                                  {
    
                                      log.Info("Trying to reconnect" + "\n");
                                      log.Info(ws.State);
    
                                      if (!(ws.State.ToString().Equals("Open")) && !(ws.State.ToString().Equals("Connecting")))
                                      {
                                          ws.Open();
                                          await Task.Delay(2000);
                                      }
                                      else if(ws.State.ToString().Equals("Open"))
                                      {
                                          retry = false;
                                      }
                                     
                                  }
                              };
                    ws.Open();
                });
                //log.Info("Exiting  webSocketConnect method");
            }'

**Comment by hjchan** [comment]
Hi @dhinesh-raja is this related to bountysource?
