### ISSUE TITLE
Unable to make changes to primeNG source code to modify span element for dropdown

### ISSUE THREAD

**Issue by jasmeet167** [bountysource/core#1113]
I want to assign unique class name to each span element created for dropdown items, but adding class = SelectedOption to the span element in source code adds this same class name to all dropdown options.How can i assign a unique class name to each span element (corrosponding to each dropdown value) to indentify each item with a unique class name. 

Any help is greatly appreciated.
Thanks in advance!

**Comment by jasmeet167** [comment]
Below is the primeng source code for dropdown component:

  <div #itemswrapper class="ui-dropdown-items-wrapper" [style.max-height]="scrollHeight||'auto'">
                    <ul class="ui-dropdown-items ui-dropdown-list ui-widget-content ui-widget ui-corner-all ui-helper-reset" *ngIf="panelVisible">
                        <li *ngFor="let option of optionsToDisplay;let i=index" 
                            [ngClass]="{'ui-dropdown-item ui-corner-all':true, 'ui-state-highlight':(selectedOption == option), 
                            'ui-dropdown-item-empty':!option.label||option.label.length === 0}"
                            (click)="onItemClick($event, option)">
                            <span class = SelectedOption *ngIf="!itemTemplate">{{option.label||'empty'}}</span>
                            <ng-template [pTemplateWrapper]="itemTemplate" [item]="option" *ngIf="itemTemplate"></ng-template>
                        </li>
                    </ul>
                </div>

**Comment by hjchan** [comment]
Hi @jasmeet167 is this related to bountysource?
