### ISSUE TITLE
Why are you ripping all issues from github

### ISSUE THREAD

**Issue by untotren** [bountysource/core#1114]
Whenever I post an issue in Github I see it posted then on your site.  Without my consent, request, etc.  Why?  Do you have permission from Github?   This seems quite invasive to say the least.

**Comment by 3rdwiki** [comment]
That's the idea of free culture ...... dude.

**Comment by juanj** [comment]
I think if they have an API token then they have "permission from Github".

**Comment by untotren** [comment]
Underhanded taking advantage of consent with fine print is just always shameful.

**Comment by rappo** [comment]
I'm pretty sure you're trolling, but if you're not... please go make yourself comfortable with the basic ideas behind f/oss. We have educational links in our footer and FAQ and I'm sure other participants in this thread would be happy to help.

> Do you have permission from Github? 

Yes, we have API access.

> This seems quite invasive to say the least.

... [?]

**Comment by untotren** [comment]
I am sure most users do not post on Github and expect third party sites to rip the content since they cannot get users to make content on their own site organically.

**Comment by LordSpacehog** [comment]
@untotren,

The key words there being "through GitHub's functionality" if you want your info to be private don't post on public repos. Do you take issue with google indexing GitHub content?

If bountysource was in any way violating ToS they'd have their api access revoked.

**Comment by untotren** [comment]
" reproduce your Content solely on GitHub as permitted through GitHub's functionality."

It says you can use the functionality to reproduce content, solely on Github.  Regardless, I as a user, feel violated to have my posts made, username replicated etc and as Github states, I own my content, so I would like it removed.  I reported this to github and FTC already, I will finish my DMCA and let the powers that be make their judgement.

**Comment by LordSpacehog** [comment]
@untotren

This is all pretty amusing considering that a decent chunk of your repositories and comments are all on projects designed for use in online piracy. So is stealing other peoples content ok, but using publicly available posts through legitimate avenues within the rights granted from the ToS of the service in question not ok? Maybe you should take a step back and seriously re-evaluate your internal cognitive dissonance.

**Comment by untotren** [comment]
Oh stop whining, if you did nothing wrong, you have nothing to worry about.  I use my software for personal use, not like you, using it for commercial gain.  We will see what they say, glhf.

**Comment by untotren** [comment]
Funny that you use ad hominem character attacks instead of addressing the points.  Indicators of a guilty man lol

**Comment by LordSpacehog** [comment]
It's not a character attack to point out the hypocrisy of your complaint here (even if it did have any actual merit) when you yourself publicly associate with projects that enable piracy. Bountysource isn't even the only project on the web to utilize the github API, godoc and a number of other projects also process PUBLIC activity on github to provide useful services to average users. Additionally if you'd care to look at any of the other dicussions and issues in this repo or over on the boutysource site you'd realize that they're effectively making enough money to keep the site running, so i'd hardly qualify that as "financial gain". In the future might i suggest taking a less entitled and more even keel approach. You'd likely get a much more favorable response from people, or at least come away with some understanding of why things were done in the way they were. If you're also concerned about your privacy maybe you shouldn't be posting things on publicly indexable and viewable repos. To me that seems to just be basic common sense.

**Comment by untotren** [comment]
I own my content, I want it taken down.
