### ISSUE TITLE
GitHub avatar/profile image is incorrect

### ISSUE THREAD

**Issue by gingerbeardman** [bountysource/core#1115]
I registered with BountySource today, using GitHub to do so.

I immediately noticed that my avatar/profile photo is inncorrect.

https://www.bountysource.com/settings

![screen shot 2017-07-07 at 16 37 23](https://user-images.githubusercontent.com/49612/27965136-98f3a432-6332-11e7-875b-b2f6126968e6.png)

I've not used this avatar/profile image for quite some time.

As a workaround I'm using my gravatar.

**Comment by tues** [comment]
I signed in using GitHub as well, but in my case there's no avatar at all:
![bountysource-avatar1](https://user-images.githubusercontent.com/1550710/28460667-45b568be-6e13-11e7-91db-1fd13653914d.png)
I also set up gravatar, but it doesn't work either.

What's worse, I can't sign up without using GH now (`Email has already been taken`), so can't test if it works with normal accounts.

**Comment by Tecktron** [comment]
I also signup up with Github and I have the same issue in that it doesn't pull the avatar. 
Having worked with the Github OAuth system myself (although not in ruby) I see this as an issue with the integration.

**Comment by JalenOng** [comment]
Issue closed and merged with master

**Comment by gingerbeardman** [comment]
@jalenong so is this fixed?

**Comment by JalenOng** [comment]
Yes it is. Please let me know if you face any issues :)

**Comment by gingerbeardman** [comment]
I'm still seeing the wrong avatar

**Comment by JalenOng** [comment]
The avatars in your profile settings are from the linked accounts you have, either on Facebook, Twitter or GitHub. If you hover your mouse over them, it shows you which linked account it comes from :)

**Comment by gingerbeardman** [comment]
After your last comment, I was seeing different images in those three positions (current, GitHub, Twitter). Only GitHub was correct. 

But now I am checking again and they are all the same, correct image. I guess there was a delay for them to update?

Anyway, thanks for solving this!
