### ISSUE TITLE
Setup an IRC <-> Slack bridge

### ISSUE THREAD

**Issue by rappo** [bountysource/core#1116]
I'd like to have #bountysource (IRC Freenode) linked with #public on https://bountysource.slack.com/.

Can someone setup a bot to do this?

**Comment by lukespragg** [comment]
https://github.com/42wim/matterbridge works great for this, I use it for IRC + Slack + Discord bridging (I don't have a stable host right now though.)

Config example: https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample

**Comment by StefanYohansson** [comment]
Hey, I want to help with this issue. I can't sign up for slack group, is it private?

**Comment by Cervator** [comment]
Hi both :-)

matterbridge would work, yep, using that to bridge some stuff over for Terasology.

@StefanYohansson yeah need an invite for Slack. Did you get in yet? Bunch of people joined recently but sometimes people use different nicks. If not you might want to lurk on IRC till you see @rappo and can ask for an invite, or get him your email in some other fashion.

**Comment by StefanYohansson** [comment]
@Cervator thanks, I had setup some bridges with matterbridge.
No, I am not registered yet on slack.
I'll try to get in touch with @rappo using IRC.

**Comment by rappo** [comment]
@StefanYohansson - sent you a Slack invite!

**Comment by StefanYohansson** [comment]
ok, I am registered on slack now.

But, I'll need a dedicated user for bot account, you can check it here:
https://github.com/42wim/matterbridge/wiki/Section-Slack-%28basic%29

> Create a dedicated user (a new account specifically for the bot) first.
> It will not relay messages from yourself if you use your account

> #You'll have to use a test/api-token using a dedicated user and not a bot token.

@rappo can you create an account and generate a token?
https://github.com/42wim/matterbridge/wiki/Slack-bot-setup

This way I can configure matterbridge to use that slack account, I don't need the acc/pass to login only the API token.

You can send it to me via email: snotr@sadfeelings.me

I can put it to work on my dedicate server and give a user for you guys or if you prefer, I can run it in one of your instances.

Regards,

**Comment by rappo** [comment]
@StefanYohansson user created ("chatbot") and slack token emailed to you. If you want to run it, that'd be awesome for getting it up and running quickly. If it becomes a burden or problem in any way we can move it off.

**Comment by Cervator** [comment]
I wonder if this might be ready to be closed as complete? :-)

Or do we need to move the bot itself to some Bountysource-controlled hosting first?

Another config example in use for Terasology (which uses a bot user despite the docs suggesting a full user is needed): https://github.com/MovingBlocks/TeraMisc/blob/master/util/matterbridge/config.toml

**Comment by rappo** [comment]
We can close this, thanks for the nudge.
