### ISSUE TITLE
Remove the hard-coded redirect of the Bountysource Team to the Salt page

### ISSUE THREAD

**Issue by rappo** [bountysource/core#1117]
Probably as simple as reverting this change https://github.com/bountysource/core/commit/35dee3c771a0a5bdac304887c8e3806f281a8093 ?

**Comment by Cervator** [comment]
Seeing occasional support requests related to confusion of the Salt URL not working (404) for teams not enabled for monthly donations. Not sure if entirely related to this issue, but maybe when fixed a nicer UX could be in place for such pages? Something simple like 

"This team is not enabled for Salt (monthly donations). Do you want to visit the team page on the regular site instead? Click here!"

**Comment by NoNonsense126** [comment]
Reverted with #1226 

@Cervator Implemented your suggestion too :)

**Comment by Cervator** [comment]
Awesome, thanks @NoNonsense126 ! :-)
