### ISSUE TITLE
PayPal Cash Out waiting

### ISSUE THREAD

**Issue by Frenzy-Alex** [bountysource/core#1123]
Hello, I requested cash out to my PayPal at Jul 17, and status is still 'Pending'. I wrote two emails to 'support@bountysource.com' but I have no answer yet. Can someone tell me how much I must waiting?
My email: oleksandr.lynok@gmail.com

**Comment by barkovv** [comment]
The bountysource team works now on the volanteer basis. Please be patient, there are some difficulties with proceeding cash out. I was waiting my BTC cash out for about 2 weeks. I guess the core team should add message about it in README's FAQ.

**Comment by dorkster** [comment]
>I guess the core team should add message about it in README's FAQ.

I agree! As it stands now, the FAQ implies cash outs will happen on Friday of the week they were requested. This can be disheartening for new bounty hunters who are unaware of the Bountysource team's state. I requested as cash out on July 16. My initial thoughts after the first week were along the lines of "did something go wrong with the request?" A bit of clarity would help alleviate situations such concerns.

**Comment by Cervator** [comment]
Just updated the FAQ in the wiki with this little disclaimer:

"Note: The timing here can vary substantially based on volunteer availability. If your request is still pending after a week or two please send us a support request and poke it occasionally until somebody can get to it"

Hardly a perfect situation but yes at least we can state it more clearly until more people are able to help process payments.

@Frenzy-Alex I see your requests in the support system, I just can't personally process them, at least not yet. So rest easy knowing it is well documented and just have patience as we catch up :-)

**Comment by jackyq2015** [comment]
I cashed out my cheque beginning of July but still hasn't received. I poked 3-4 times but just no reply. bountysource is doing this as a business, In my opinion, the payment really should NOT base on volunteer.

**Comment by Cervator** [comment]
Hi @jackyq2015 - I'm just another Bountysource user like yourself. I enjoy the service and recently volunteered to help it along. Maybe that isn't ideal but it is what little I can do personally :-)

I believe I found your entry in the support system which is probably a better place to go over the details. You should've gotten an email with a question, if not then please let me know here.

As noted there another round of cash-outs was just done a couple hours ago, maybe yours was included there? @Frenzy-Alex same question for you, although I'll probably dig through to your item in the support system soon enough if it is still pending :-)

**Comment by jackyq2015** [comment]
@Cervator Thanks! Yes I received the email this time. Hopefully I was included. :)

**Comment by jackyq2015** [comment]
Was informed that my cheque was not sent out yet for some reason. Still waiting for the update.

**Comment by rappo** [comment]
I believe all pending requests have been addressed. If not, please email support.

Thank you @Cervator for updating the FAQ.
