### ISSUE TITLE
Clarify refund policy exactly where it matters

### ISSUE THREAD

**Issue by fulldecent** [bountysource/core#1126]
Here is a box:

![screen shot 2017-07-28 at 11 18 03 am](https://user-images.githubusercontent.com/382183/28723955-709d0096-7386-11e7-9e9f-927c68f80718.png)

> Post a bounty if you want this issue solved:

It will be 100 times more helpful if you also include this text directly below:

> * Bounties of $100 or more can be refunded after 180 days if not spent
> * Bounties of $250 or more can be refunded after 90 days if not spent

---

Relevant code here:

> https://github.com/bountysource/core/blob/master/app/assets/javascripts/app/issues/_show_backer_box.html.haml

It

**Comment by rappo** [comment]
This should tie in to #1028

**Comment by kaiansaari** [comment]
@hjchan for you

**Comment by kaiansaari** [comment]
![image](https://user-images.githubusercontent.com/26814804/38398396-9ea923b8-3986-11e8-960f-659f6ddfada9.png)
Updated!

**Comment by fulldecent** [comment]
Looks great, thank you.
