### ISSUE TITLE
Team section only shows 30 projects on GitHub Committer Tools page

### ISSUE THREAD

**Issue by DivineOmega** [bountysource/core#1127]
After creating a team from a GitHub organisation, we started activating the GitHub Committer Tools on some of the repositories at the following URL.

https://www.bountysource.com/tools

This mostly works fine. However, we have noticed that only the 30 repositories appear in this list under the team/organisation's name. They appear to be the first 30 repositories that were created. Personal (non-team) accounts seem to show all repositories correctly (not limited to 30).

GitHub appears to show 30 repositories per page, so perhaps Bountysource is only getting 1 page worth of repositories via GitHub's API.

This is the GitHub organisation we're using: https://github.com/rapidwebltd/

**Comment by hjchan** [comment]
fixed in e3fdbe5

**Comment by DivineOmega** [comment]
@hjchan Thanks!
