### ISSUE TITLE
Issues failing to import from Bugzilla

### ISSUE THREAD

**Issue by ashley-rose** [bountysource/core#1128]
I was trying to post a bounty for bug [193121](https://bugzilla.kernel.org/show_bug.cgi?id=193121) on the kernel.org bugzilla instance. When I do, it creates a closed issue on bounty source with no opportunity to actually reopen it. ([example](https://www.bountysource.com/issues/48109957-193121-brcmfmac-working-extremely-poorly-on-macbookpro13))

**Comment by Cervator** [comment]
Bump - seeing this pop back up on occasion. Added a $50 bounty for anybody willing to help out getting it fixed :-)

**Comment by polarathene** [comment]
A bounty to fix bountysource? aha!

I contacted them a couple weeks ago and got directed here, considering it's the linux kernels bug tracker and thus blocking any bounties on it, you'd think this would be more of a priority :( I am part of a community that wants to pledge towards seeing a bug fixed, quite a few from the community are waiting on this.

**Comment by Cervator** [comment]
Yeah the bounty I placed is actually *from* Bountysource as I'm a fairly recent new volunteer, with access to a little pool of funds to place bounties with. The founders are occupied elsewhere and I'm not at all up to date on the code here yet. So time is a problem, but small bounties are easy to at least place.

Got my own open source projects to worry about, but I want to use Bountysource so I'm doing what little I can on the side :-)

**Comment by NoNonsenseSolutions** [comment]
#1230

**Comment by NoNonsense126** [comment]
Merged and fixed
