### ISSUE TITLE
Problems with the standardized setup

### ISSUE THREAD

**Issue by Denu8thell** [bountysource/core#1134]
As it stands, the "standardized" setup is insufficient. I think it's really close, but it needs a few tweaks. 

1. it seems that docker-compose build makes a  docker image "core_bountysource" instead of just "bountysource". This leads to issues when running the server or any of the tasks, causing them to fail.

2. The current setup doesn't seem to allow for rapid development (I think you have to rebuild the image everytime you make a change?). 

These two combined lead to confusion for potential developers who want to help out with bountysource, and it's just no fun to spend hours figuring out why your local copy won't run correctly, even when you followed the instructions to a T.

Past that, I'd also like to have a way to set up some SMTP stuff, so you can actually see if mailers are working correctly.

Anyone else run into the above two problems?

**Comment by Denu8thell** [comment]
For the record, the fixes are:

1. add `image: bountysource` under the bountysource service in docker-compose.yml
2. change all instances of `app:/app` under the volumes sections to '.:/app' in both docker-compose.yml and tasks.yml. You can remove the `app:` entry in the top level volumes in both files as well.

**Comment by vigasdeep** [comment]
Thanks for thinking about us :)
1. Yes I faced this problem, figured the solution by looking at error.
2. Did not face anything like that: how to check?

**Comment by Denu8thell** [comment]
@vigasdeep To reproduce the second problem, you should change something in the code, then reload the webpage. It doesn't update. It doesn't update even if you 'docker-compose down' and 'docker-compose up'. 

My recommended way to check is to edit the navbar, which is quick and easy to see. go to 'app/assets/javascripts/layout/navbar.html.erb', and on line six replace "Bountysource-green.png" with "Bountysource-white.png". Save the file, then reload the webpage in your browser. If the logo in the upper left changed white, you do not have this problem. If it is still green, then you DO have this problem. It will stay green until you (presumably) rebuild the bountysource docker image.

**Comment by vigasdeep** [comment]
@Denu8thell am I supposed to do this on the main repository code? OR after logging into docker container by doing: 'docker-compose run bountysource bash', and then edit?

**Comment by Denu8thell** [comment]
You should do this on your host file system, where you cloned the repo. (main repository code) 

You shouldn't HAVE to edit from the bash shell. If you use the bash shell in the container, then yeah, your changes will work.

**Comment by vigasdeep** [comment]
Okay so I assume this is the file : app/assets/javascripts/**app**/layout/navbar.html.erb

**Comment by Denu8thell** [comment]
Yup, nice catch.

**Comment by vigasdeep** [comment]
Yes I do have second problem as well. But there is another problem, logo doesn't change even after rebuilding, I used the same command to which I previously used for initial build: 'docker-compose -f docker-compose.yml build'

**Comment by Denu8thell** [comment]
See, that's a problem. Apparently not even rebuilding allows changes in those directories to seep in. I'm guessing docker's assuming that the source files are unchanged or something. The above fix actually mounts the directory instead of having it copied when initially built, so any changes are immediate, and I think that's better for development.

**Comment by vigasdeep** [comment]
Ahan! that's better, I didn't have to rebuild or anything else, now every change I make, I can see with a browser refresh. Thanks. This should be sent as PR, no?

**Comment by Denu8thell** [comment]
Yeah, I'll put in a PR for the fixes, I'm convinced that this is an actual issue now.
