### ISSUE TITLE
Add Bitcoin Cash support to BountySource

### ISSUE THREAD

**Issue by abrkn** [bountysource/core#1136]
![](https://api.bountysource.com/badge/issue?issue_id=49027183)

> Bitcoin Cash brings sound money to the world.  Merchants and users are empowered with low fees and reliable confirmations. The future shines brightly with unrestricted growth, global adoption, permissionless innovation, and decentralized development.

https://www.bitcoincash.org/

**Comment by lvella** [comment]
BountySource should not only accept Bitcoin Cash, but store and list the bounty in it!

So it should say, "Bounty of: $ 245,00 + B 0.12435320". Pay received dollars in dollars, and received BCH in BCH.

**Comment by abrkn** [comment]
We have a logo!

https://github.com/DarrenRM/bcash-logo/issues/3#issuecomment-327909297

![](https://github.com/DarrenRM/bcash-logo/blob/master/bcash-greensquare.png?raw=true)

**Comment by EchterAgo** [comment]
Please do not use the Bcash logo, use the official Bitcoin Cash logo from their website:

https://github.com/bitcoincashorg/website/blob/master/html/img/bitcoincash-white.png
https://github.com/bitcoincashorg/website/blob/master/html/img/bitcoincash.png

It is licensed under the MIT license:

https://github.com/bitcoincashorg/website/blob/master/COPYING

**Comment by omersiar** [comment]
How do you Bountsource guys even support Bitcoin with these fees already?

**Comment by Cervator** [comment]
> How do you Bountsource guys even support Bitcoin with these fees already?

Reluctantly? :/

**Comment by abrkn** [comment]
This bounty is still open. Do you have any plans to add Bitcoin Cash support? BountySource is no longer usable for me with > $15 BTC network fees.

**Comment by omersiar** [comment]
@abrkn Hello can you please remove the green logo? I believe Bitcoin Cash community mostly agreed on this one : 

https://github.com/bitcoincashorg/website/blob/master/html/img/bitcoincash.png

**Comment by abrkn** [comment]
Updated, @omersiar

**Comment by chaintip** [comment]
Until they add Bitcoin Cash and even after they add Bitcoin Cash...

Letting you know that ChainTip is another option for you.

https://github.com/chaintip/bounties

Bitcoin Cash only, no fees. GitHub bounties only at the moment.

**Comment by kaiansaari** [comment]
@abrkn we are busy building out crypto bounties with the first iteration handling eth & erc20 tokens. Bounties will be either USD or crypto and be posted/listed in the cryptocurrency. eg. 1 Eth, 200 OMG, 100 KNC etc. 

From a timing perspective i'd say once we have the crypto payment MVP we would be interested in featuring crypto payment related bounties including this one for Bitcoin Cash (BCH).

**Comment by programizer** [comment]
[Here](https://gist.github.com/programizer/8c829801779240353497e07e410c2c3a) is a first gist for using Coinbase commerce API in bountysource (which includes Bitcoin cash support).

**Comment by programizer** [comment]
@kaiansaari Is there a fair chance that you would accept a pull request that features Coinbase Commerce API support in bountysource?

**Comment by programizer** [comment]
Ok, you seem to have you own approach for the native support alternative...

**Comment by eljefuri** [comment]
Any crypto support is welcomed. @kaiansaari off-topic but when does ERC20 support roll out?

**Comment by XVilka** [comment]
For those who is still curious in BCH bounties - there is an open-source and free of charge alternative, that supports various cryptocurrencies and allows to set bounties on GitHub issues - [jollheef/donate](https://github.com/jollheef/donate).

This is how it looks [in the GitHub issue](https://github.com/jollheef/donate/issues/8)

![image](https://user-images.githubusercontent.com/203261/73710690-a978cf00-473f-11ea-80be-a2e62dad2f27.png)

**Comment by vibhuti019** [comment]
Is this still open? 
I would like to work on this.

**Comment by abrkn** [comment]
No
