### ISSUE TITLE
Payout not received after 2 and a half month

### ISSUE THREAD

**Issue by jackyq2015** [bountysource/core#1139]
I submitted request on Jul 7 and still haven't received the cheque. Last time I received email from Rasmus Praestholm  week ago told me that " I haven't been able to get a hold of Rappo at all for a little while now. I hope he's okay and will be back in touch soon". But still I haven't get update until now. It make me raise some concern about the company. Not sure it is a common issue or just happened to me ? Hopefully bountysource can address this asap.

Amount | Submitted | Status | Payment Method
$310.00 | Jul 7, 2017 | Pending | Check

[bounty number](https://www.bountysource.com/issues/46532977-extend-cross-function-to-take-either-a-cell-or-a-value)

**Comment by barkovv** [comment]
Payout delays are reqular here. Now there is some work to include this stuff (see #1079 and #1080 ). The reason is that @rappo is working on the volunteer basis. I think the core team should add some info to README or FAQ with this information since it's a common issue here.

PS
Usually I am waiting my cashouts for about 1 month here.

**Comment by jackyq2015** [comment]
Is it possible to help to check this [bounty number](https://www.bountysource.com/issues/46532977-extend-cross-function-to-take-either-a-cell-or-a-value) since it has been already 2.5 months?

**Comment by Cervator** [comment]
Hey again.

Yep still trying to reach out and help get pay-outs more stable again. It is a common issue - just worse at times.

I haven't had time for support replies for a few days, but will find yours and check on it again soon - just looking real quick right now it appears to be paid out but maybe something went wrong around the very end somehow. Not sure I have access to dig deeper at the moment.

**Comment by gnidorah** [comment]
@Cervator Please look for mine too:
```
Amount | Submitted | Status | Payment Method
$350.00 | Aug 30, 2017 | Pending | Paypal
```
https://www.bountysource.com/issues/45363539-sql-error-when-retry-of-multipart-message + https://www.bountysource.com/issues/41969673-sentitems-table-sending-status-number
Thank you!

**Comment by jackyq2015** [comment]
received
