### ISSUE TITLE
Some bounty pages pulling up blank

### ISSUE THREAD

**Issue by Cervator** [bountysource/core#1140]
(Edit: this issue itself has a bounty on it, see https://www.bountysource.com/issues/49557512-some-bounty-pages-pulling-up-blank)

Yet the vast majority work fine. Unsure what is causing specific pages to load empty. In the admin system I can see the issues normally as well as the attached bounties etc.

Two example pages that load blank for the user who reported them as well as me in Chrome, IE, Firefox on Win 10 and Chrome on Android:

* https://www.bountysource.com/issues/5242562-regression-neo-layout-layer-3-4-broken
* https://www.bountysource.com/issues/44030981-cursor-jumps-back-and-forward-several-times-on-switching

*Maybe* related: #1098 ? Could be interesting to see if simply submitting new issues then moving the bounty would solve the issue, especially if the exact same text is used in the issue body. Might work as a workaround.

This is naturally very disturbing especially if users are submitting bounties then believing they've gone missing. Even if the bounty does make it to the issue on the Bountysource side that doesn't help a whole lot if nobody can see or work them publicly.

**Comment by Marenz** [comment]
Here are more issues with this problem: 

* https://www.bountysource.com/issues/815255-pgp-mime
* https://www.bountysource.com/issues/3432158-google-wallet-outbound-bridge-plugin

**Comment by Marenz** [comment]
Looking at the requests happening in the background, I can see this suspicious call that results in 404:

`https://api.bountysource.com/badge/issue?issue_id=undefined`

**Comment by Cervator** [comment]
Thanks for that @Marenz !

I don't have access to the server logs yet or enough knowledge of the code to dig much deeper, but that *should* help narrow the problem down a bit.

Comparing the issues and what I can see in the admin system (not everything, like peering into the DB itself - can't do that yet either) doesn't show anything obvious like specific things in the issue body (like a badge), and it is affecting different trackers. Maybe something is checking for badges anyway and in some cases not able to formulate a good request.

Example raw issue on GitHub for the Synergy issue: https://api.github.com/repos/symless/synergy-core/issues/5992

**Comment by Cervator** [comment]
Additional example: https://www.bountysource.com/issues/23988054-please-consider-an-official-debian-package

That one is even more odd and interesting. Tracker is launchpad, exact URL is https://bugs.launchpad.net/audio-recorder/+bug/1391951

First time I tried to load the bountysource URL it pulled up blank. A few minutes later it pulled up without comments in status closed. Then a few minutes later it was blank again. Yet another few minutes later it pulled up with several comments visible.

CoderEurope on IRC mentioned it:

```
7:39:37 PM - CoderEurope: funny thing was - after 20 mins the original launchpad page was expenaded to an extra two comments (?)
7:39:40 PM - Cervator: done and edited the issue itself
7:40:44 PM - Cervator: unsure about that expanded comments bit
7:40:58 PM - CoderEurope: sorry - let me clarify
7:41:20 PM - CoderEurope: so I added the launchpad page to the bountysource search bar .....
7:41:49 PM - CoderEurope: and one launchpad comment appeared on the bountysource page
7:42:14 PM - CoderEurope: then after I re-loaded the bountysource page in 20 minutes .....
7:42:16 PM - Cervator: oh, and now it doesn't load blank anymore either
7:42:22 PM - Cervator: showing as closed
7:42:43 PM - CoderEurope: two extra launchpad comments appeared on the bountysource page
7:43:43 PM - CoderEurope: Cervator: if you look at the launchpad page - you shall see it has 'transfered' to another part of launchpad - which I am finding hard to find.
7:44:05 PM - Cervator: i see the bountysource page now without comments, showing closed. But before it was entirely blank. Interesting
7:45:04 PM - CoderEurope: ... so I am finding it hard to find where the launchpad bug has transfered to on launchpad itself.
7:45:35 PM - Cervator: yeah i'm not spotting anything obvious that links to it either
7:45:46 PM - Cervator: but that would explain why the status on Bountysource has become closed
```

**Comment by xet7** [comment]
I think integration with GitHub is broken, because also GitHub login to BountySource does not work for me. I did mention about it at Freenode IRC a moment ago.

**Comment by Cervator** [comment]
Hey @xet7 - the login issue is separate. See #1145 / #1147

**Comment by mathias-baumann-sociomantic** [comment]
This issue is still ongoing.. I still can't pull up the *my* bounty: https://www.bountysource.com/issues/5242562-regression-neo-layout-layer-3-4-broken and it makes me very sad.

**Comment by NoNonsense126** [comment]
@mathias-baumann-sociomantic I've hotfixed it for your issue, pending debugging
