### ISSUE TITLE
GitHub Commiter Tools doesn't work

### ISSUE THREAD

**Issue by Diaoul** [bountysource/core#1142]
I think it's been a year now that the GitHub Commiter Tools doesn't work for https://github.com/SynoCommunity/spksrc/
In addition to wait for the bug to resolve itself over a long period of time, I've tried to tick/untick the checkboxes for integration without luck.

Here is an example of an issue that received a bounty recently but I updated the tags and title manually : https://github.com/SynoCommunity/spksrc/issues/2939

**Comment by Denu8thell** [comment]
Duplicate of #1096?

**Comment by rappo** [comment]
yes, dupe of #1096
