### ISSUE TITLE
Cashout request

### ISSUE THREAD

**Issue by Nemixalone** [bountysource/core#1146]
Its been three weeks now and no mail have  helped to push a cashout request to PayPal. Is it possible to cashout asap? My mail is nemixalone@gmail.com 
Thanks.

**Comment by Cervator** [comment]
Just to leave the resolution on here for clarity: I believe this was completed :-)

Please let us know if not and thank you!

**Comment by Nemixalone** [comment]
Thank you very much 😊😊
