### ISSUE TITLE
Bountysource non-responsive to customer requests.

### ISSUE THREAD

**Issue by Symbolics** [bountysource/core#1160]
I have encountered a bug whereby I cannot use my contributions to post bounties. Several emails to support have gone unanswered after three weeks.

Attempted to cancel contributions, but nowhere on the website can this be done. Perhaps related to the bug on not being able to post bounties.

No phone number to call.

Matter referred to credit card company.

**Comment by rappo** [comment]
Hi @Symbolics, I see your ticket in our support queue and I'll take a look right now. We're volunteers on Bountysource, so response time isn't as fast a major commercial outlet, unfortunately. I do see that your team account has a cashout pending for the full balance, which is why you can't create a bounty from your team balance (which is effectively $0. I'll take that up with you in Support as GitHub is for bugs and feature requests.

**Comment by Symbolics** [comment]
Thank you Rappo.

Note that I do not _want_ to cash out: I want to post bounties. I only tried the cash-out because no one was responding to my requests for help.

**Comment by Symbolics** [comment]
@rappo, Just to confirm: I was unable to create bounties _before_ trying to cash out. That was the problem I am trying to solve.

**Comment by rappo** [comment]
Noted, I've refunded your cash out request. Can you link me an example issue that you were trying to put a bounty on?

**Comment by Symbolics** [comment]
Text of the email here:

Dear BountySource,

It seems I am unable to use any of my funds to place bounties. For example when I look at one of the issues for the team:

https://www.bountysource.com/issues/52180942-define-presentation-method-broken-on-ccl

and click on one of the dollar amounts under the 'Backers' section, nothing happens. No error, no beep, nothing.

I've also noticed that under 'Managing Projects': Bountysource, when I try to add the github issue tracker (https://github.com/Symbolics/), nothing happens there either. I have not been able to find anything in the documentation or FAQ on this topic.

What do I have to do to post bounties?

Regards,
    - Steve Nunez

**Comment by Symbolics** [comment]
@rappo I would request that you refund the full amount if you do not mind. The only reason for the cash-out was because I could not post bounties and received no response from support.

**Comment by Symbolics** [comment]
@rappo, I see you did refund the full amount. Thank you very much.
