### ISSUE TITLE
Website doesn't work

### ISSUE THREAD

**Issue by yelizariev** [bountysource/core#1161]
https://www.bountysource.com/

> Application error
> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

**Comment by yelizariev** [comment]
ok, works now

**Comment by yelizariev** [comment]
api.bountysource.com work too slowly or doesn't work at all. I cannot sign in. It shows Application error

**Comment by jpturcotte** [comment]
Yep, same thing on my end: a Heroku "Application error" page.

**Comment by wkonkel** [comment]
Resolved, sorry everybody!
