### ISSUE TITLE
Cannot uninstall Bountysource from a repository

### ISSUE THREAD

**Issue by dessant** [bountysource/core#1164]
There is an uninstall button in the source, but it is hidden and does not seem to work. How can we uninstall Bountysource from a repository?

![screenshot from 2017-12-20 15-41-24](https://user-images.githubusercontent.com/7513068/34209828-6bd956e4-e59c-11e7-8f33-84e316764a31.png)

**Comment by hjchan** [comment]
duplicate of #1009
