### ISSUE TITLE
BountySource says cash-out made 14 Dec, PayPal says no deposit

### ISSUE THREAD

**Issue by Symbolics** [bountysource/core#1165]
I made a request for a cash-out, and on 14 December my account page shows it was made to PayPal. However the money never arrived at PayPal and today is the 21st. 

When will the cash-out arrive?

**Comment by Symbolics** [comment]
Anything guys? Money taken, no refund, no answer from support. Something is not right here.

**Comment by Symbolics** [comment]
It has been a month now. How much longer before I can expect the refund?

**Comment by rappo** [comment]
@Symbolics there 3 different communication channels open now and it's getting hard to track, let's stick to one. support@bountysource is the best place for support (github is for software issues / feature requests). I think I understand what the issue / miscommunication is now, I'll follow up with you very shortly via email.
