### ISSUE TITLE
No fees for 60 days?

### ISSUE THREAD

**Issue by dom96** [bountysource/core#1170]
What's the story behind this commit? https://github.com/bountysource/core/commit/4442002f72d8e577085eaa1a39e7cf2eba749ae5

Why are no fees being taken for 60 days?

**Comment by Cervator** [comment]
Heya @dom96 - at this point maybe you've come across the details, but just to add them here Bountysource was acquired by CanYa and to celebrate the fees have gone on vacation for two months :-)

Blog post with more details: https://blog.canya.com.au/2017/12/20/canya-acquires-majority-stake-in-bountysource-adds-over-46000-users/

Closing this as answered but if you have more questions feel free to ask somewhere
