### ISSUE TITLE
"Find bounties" sorted by age start at 2 years old

### ISSUE THREAD

**Issue by janat08** [bountysource/core#1172]
https://www.bountysource.com/bounties/search?direction=desc&order=earliest_bounty&languages=&trackers=&per_page=50&page=1

Would be great if paid out or closed issues could be filtered out, besides not ascending from 2 years back.

**Comment by xloem** [comment]
I put a bounty on this at https://www.bountysource.com/issues/53634683-find-bounties-sorted-by-age-start-at-2-ages-old

**Comment by xloem** [comment]
This appears to have been fixed on the live site.  Unsure who fixed it, but it seems to me the bug should be closed.
