### ISSUE TITLE
Cannot use twitter image on my profile

### ISSUE THREAD

**Issue by steff1193** [bountysource/core#1200]
After having linked my twitter account, my twitter image is available in profile settings. Selecting it and pressing "Save" results in: Unable to update account: Image url not recognized: twitter:

**Comment by steff1193** [comment]
And it does not seem that it is able to fetch my GitHub image either.

**Comment by kaiansaari** [comment]
Hi @steff1193 we'll sort this out for you.

**Comment by NoNonsense126** [comment]
Should be fixed so that both works now
