### ISSUE TITLE
how do I opt-out of bountysource

### ISSUE THREAD

**Issue by jrochkind** [bountysource/core#1201]
I have github projects listed on bountysource. I do not want them there. How do I opt out?

I could not find any information in wiki, readme, source code, or googling.

**Comment by Cervator** [comment]
Hey there. There is a process, it is just very new. It is listed in the privacy policy but could probably be made more visible.

In short: mail support@bountysource.com with a "Takedown Request" then include links and details for what you'd like taken down, along with some sort of proof that you own the repos in the email. Easy enough :-)

**Comment by Cervator** [comment]
Not sure if you've emailed support yet, cannot find an obvious request there, but that's the route to take. Please proceed at your convenience, I'm going to go ahead and close this issue awaiting the email request :-)

**Comment by jrochkind** [comment]
This is not super convenient, but okay.   Can you add here what sort of proof that you own a github repo you would like included in the email, to save a step of back and forth? It's not clear to me how to incude proof of github ownership in an email. Putting it here in this ticket will be findable by others later too.

**Comment by Cervator** [comment]
Easiest way is probably make sure your email is visible somewhere on your GitHub account (temporarily if needed) then send the support request using that email. Or just log in on the site using GitHub as the login method. Then any repos under your account or organizations you're listed as a public member on would be pretty well covered :-)
