### ISSUE TITLE
No redirection from bountysource.com to www.bountysource.com

### ISSUE THREAD

**Issue by Flaburgan** [bountysource/core#1202]
Entering bountysource.com actually returns a [very weird XML document](https://gist.github.com/Flaburgan/b6229049eff604c81158a5dfe4507a5d)

**Comment by NoNonsense126** [comment]
The DNS redirect should be fixed now. Let me know if it isn't. Thanks!

**Comment by Flaburgan** [comment]
Looks like it works, thank you.
