### ISSUE TITLE
Investigate Shopping Cart issue

### ISSUE THREAD

**Issue by rappo** [bountysource/core#1219]
1. User checks out via paypal/coinbase
2. Payment is made and accepted via Paypal
3. User is redirected back to Bountysource but the cart has not been processed

**Comment by NoNonsense126** [comment]
Was the shopping cart never processed? Was it processed a little later? If the latter, I think this could be due to a delay on paypal's IPN.

**Comment by rappo** [comment]
Cart never gets processed. The cart will actually persist (and we could manually process it from the backend).
