### ISSUE TITLE
Not all bounties counted to project

### ISSUE THREAD

**Issue by funjoker** [bountysource/core#1242]
Inside the Issue list you can see all bounties.

On team site you only see the once of master branch?

Example:
https://www.bountysource.com/teams/trinitycore/bounties ( 2 bounties 65$ shown)
https://www.bountysource.com/teams/trinitycore/issues (23 bounties value of 990$)

Show all active bounties on team site

**Comment by hjchan** [comment]
I guess there is some misunderstanding about the bounties and the issue page.

https://www.bountysource.com/teams/trinitycore/bounties will show the bounties posted by this team whereas https://www.bountysource.com/teams/trinitycore/issues show the issues and bounties of those issues. 

Hope this clarifies.

**Comment by funjoker** [comment]
Oh i See

**Comment by Flaburgan** [comment]
I would say +1 to see. I'm often confused about it, and I don't see the value for the user added by that filter (access only to the bounties posted by the team). In my opinion, the "issues" tab should list **all** issues, possibly ordered by vote, including the ones without any bounties, to allow users to put bounty on it / vote on it, whereas the "bounties" tab should list all issues with a bounty on it, ordered from the highest reward to the lowest reward.

**Comment by funjoker** [comment]
You can order the issues by bounty, just change the order style to a List ad then click in the bounty column to sort.
