### ISSUE TITLE
Project search yields no meaningful results

### ISSUE THREAD

**Issue by PhrozenByte** [bountysource/core#1343]
I'm trying to add the `picocms/Pico` repo to https://www.bountysource.com/teams/picocms, but this seems to be virtually impossible.

First of all, if I search for `picocms/`, I'd expect to get a list of repos owned by @picocms, but @picocms isn't even in the list (`Tyxiang/picocms.github.io` is listed three times?):

![bildschirmfoto am 2018-06-24 um 17 16 30-fullpage](https://user-images.githubusercontent.com/920356/41820459-8cf3611c-77d2-11e8-9116-289fa3b98b12.png)

Even if I search for `picocms/Pico`, **a exact match** of the repo I'm trying to add, the desired repo still isn't in the list:

![bildschirmfoto am 2018-06-24 um 17 18 54-fullpage](https://user-images.githubusercontent.com/920356/41820476-b038daf8-77d2-11e8-98d5-e198480bfa49.png)

Due to this bug, it's currently impossible to use Bountysource :disappointed:

**Comment by NoNonsense126** [comment]
@PhrozenByte You should be able to find your repository now.

**Comment by PhrozenByte** [comment]
Thank you for the really fast response @NoNonsense126!

After claiming the (automatically created) [`picocms-pico` team](https://www.bountysource.com/teams/picocms-pico) that owned the [`picocms/Pico` repo](https://github.com/picocms/Pico) at this time (btw: is it intentional that there's no error message that claiming a already assigned repo isn't possible?) and deleting the repo there, I was able to add it to the [`picocms` team](https://www.bountysource.com/teams/picocms).

Now I'm trying to add some of our official plugins (which are intentionally owned by their respective creator) to the [`picocms` team](https://www.bountysource.com/teams/picocms). Namely I'm trying to add the [`PhrozenByte/pico-admin`](https://github.com/PhrozenByte/pico-admin), [`PhrozenByte/pico-robots`](https://github.com/PhrozenByte/pico-robots) and [`PhrozenByte/pico-http-params`](https://github.com/PhrozenByte/pico-http-params) repos. Unfortunately it isn't possible to add these repos because the search terms (exact matches of the repo names) yield no results:

![screenshot-2018-6-27 pico - teams](https://user-images.githubusercontent.com/920356/41991997-951dffba-7a47-11e8-8927-4f130b329817.png)

**Comment by NoNonsense126** [comment]
You’ll need to paste the url of the repositories into the search bar in the navbar. This allows bountysource to create a tracker based on the repo. 

I’ve done so for pico-admin, so you’ll be able to find it there. You can do the same for the other repos.

Apologies that there are some UX problems with the site.

**Comment by PhrozenByte** [comment]
Got it, it works! Thanks again for the really fast response! :+1:
