### ISSUE TITLE
Bugs on debbugs.gnu.org immediatly marked as closed (when it's still open)

### ISSUE THREAD

**Issue by ideasman42** [bountysource/core#1345]
I've reported a bug: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30750

And a bounty source link: https://www.bountysource.com/issues/60318530-30750-25-3-new-python3-6-f-string-syntax-highlighting-support-feature-request-gnu-bug-report-logs

The issue was immediately marked as closed.
Even though as far as I can see the issue is still open.

**Comment by NoNonsense126** [comment]
Hi this bug tracker is not supported as of this moment

**Comment by ideasman42** [comment]
It would be good if the interface didn't let you report the issue, instead of accepting and marking as closed.
