### ISSUE TITLE
Invalid project logo URL

### ISSUE THREAD

**Issue by amitguptagwl** [bountysource/core#1348]
I've recently created a project/team on salt.bountysource : https://salt.bountysource.com/teams/imglab

Unfortunately as  it appends a query parameter to resize the image `&s=400`, is syntactically wrong. Hence the project page doesn't show the image (404).

Can you please fix it?

**Comment by KhaledHamoul** [comment]
use this link for your logo [](https://res.cloudinary.com/darogtcc4/image/upload/v1547772023/imglab_logo.png)
instead of the Github link.
here is the prouve that's working now [](https://www.bountysource.com/teams/khaledhamoul)
