### ISSUE TITLE
Internal server error when logging in with github

### ISSUE THREAD

**Issue by city41** [bountysource/core#1355]
When clicking on "sign in" then "github" on www.bountysource.com, I get redirected to 

https://api.bountysource.com/auth/github/callback?code=af0158ede278cb0b40ab&state=eyJyZWRpcmVjdF91cmwiOiJodHRwczovL3d3dy5ib3VudHlzb3VyY2UuY29tL3NpZ25pbi9jYWxsYmFjaz9wcm92aWRlcj1naXRodWJcdTAwMjZmb2xsb3dfdHJhY2tlcl9pZHM9IiwiYWNjZXNzX3Rva2VuIjpudWxsLCJpcCI6IjEwOC42OC4xMjAuMTI5IiwibXBfaWQiOiIxNjVkYjdmYjUwODEzNTItMDc3ZjhiZGFiYTZlY2QtMTgyNjEyMDItM2Y0ODAwLTE2NWRiN2ZiNTA5MTRkOCJ9

With `{"error":"Internal server error."}` displayed in the body.

This looks similar to https://github.com/bountysource/core/issues/1147 but there is no mention of the app being suspended in the url this time.

**Comment by city41** [comment]
It looks like the site in general may be experiencing issues. There's no real content on the home page and a lot of errors (most CORS related) in the console.

**Comment by mgielda** [comment]
Same here, after 11h, website is still down. Is anyone looking into it?

**Comment by bparker06** [comment]
Website is completely unusable here too.

**Comment by Cervator** [comment]
Could any of you please try to re-confirm this? I just tried with a GitHub login and everything seems fine.

**Comment by tscung** [comment]
I is working fine with my, sign in via github.

**Comment by Faq** [comment]
Works just fine. @city41 still has that issue?
