### ISSUE TITLE
[Question] Is Bounty Source only Free Software?

### ISSUE THREAD

**Issue by asdfghjz** [bountysource/core#1362]
Question: Does BountySource publish all their software under a Free Software License?

**Comment by Cervator** [comment]
To the best of my knowledge, having seen some of the stuff behind the scenes: yes. The stuff used to run Bountysource is here on GitHub and licensed under the MIT.

Caveat: I'm still just thinking of Bountysource as the core platform, but now CanYa is in the mix too. Some of those bits aren't necessarily on here, and some bits might extend Bountysource. To me the setup is that of a free open source project with a commercial backer. There may be other related things that aren't part of the Bountysource core.

In that sort of setup you're free to fork and set up an alternative, but that might take some extra work as some of the non-codey bits, especially around finances (bank accounts etc), add a fair bit of logistics, currently handled here by the CanYa team.
