### ISSUE TITLE
"Total (1item): $NaN" after adding to bounty

### ISSUE THREAD

**Issue by dandv** [bountysource/core#1368]
I've added $30 to https://www.bountysource.com/issues/1449676-add-support-for-gitlab but the confirmation message displays `$NaN` as the Total:

![image](https://user-images.githubusercontent.com/33569/51576652-f3ac4c80-1e6b-11e9-982f-d3762105436f.png)

**Comment by tuxayo** [comment]
Same.
To the devs: here is receipt that shows this issue: https://www.bountysource.com/orders/109468?receipt=1

**Comment by ThomasWaldmann** [comment]
Same here.

Also, note that the blank between "1" and "item" is missing.

**Comment by johanlives** [comment]
Solved https://github.com/bountysource/core/issues/1464
