### ISSUE TITLE
Welcome-email contains broken link

### ISSUE THREAD

**Issue by matthijskooijman** [bountysource/core#1372]
I just signed up for bountysource and got a welcome email (subject "Welcome to Bountysource!"), which contains:

> Earn money while improving open-source: Use our Bounty Search (https://www.bountysource.com/bounties/search) to discover active bounties. You can filter by project, language, bounty amount, and more.

However, the link shown (https://www.bountysource.com/bounties/search) gives a 404 (or at least shows "The content that you are looking for does not exist. Bountysource has changed!".

**Comment by johanlives** [comment]
A bounty has been placed on this issue.
Just direct back the home page on Bountysource
