### ISSUE TITLE
Trying to post a bounty with a github issue, reveals nothing.

### ISSUE THREAD

**Issue by SoylentGraham** [bountysource/core#1376]
Perhaps this is specific to my issue, but adding this link from `Post a bounty` goes to a search page with nothing on it.
https://github.com/SoylentGraham/webkit/issues/1

![Screen Shot 2019-03-26 at 16 40 39](https://user-images.githubusercontent.com/2184197/55016066-f3543d00-4fe5-11e9-9803-6f585340b261.png)

Using chrome 70.0.3 on OSX, with a twitter-linked account.

**Comment by markwkidd** [comment]
I see the same behavior with Chrome in Windows 10.

**Comment by johanlives** [comment]
If this happens again can you please email support@bountysource.com, thanks.
