### ISSUE TITLE
Not possible to close user account

### ISSUE THREAD

**Issue by fulldecent** [bountysource/core#1381]
**There is no way to delete a user account.**

I want to delete my account because of the ridiculous account inactivity fee and because there is no granularity on choosing what emails you receive. This note is beside the point and addressing my reasons to leave do not excuse the main topic of this bug report.

On the website there is no button which can be clicked to close an account. My understanding is that the current behavior violates some laws in certain US states and possibly certain European laws. I will not go find those specific legal references, it is not my responsibility to do Bountysource's legal work for them.

**Comment by jowouters** [comment]
According to GDPR (General Data Protection Regulation) all EU citizens and residents have the right to be forgotten.  These GDPR-regulations also apply to digital companies outside of the EU https://gdpr.eu/companies-outside-of-europe/  

Currently there seems to be no procedure, and no documentation, in Bountyscore on how to delete all account-related information. 

Solutions: 
1. As a minimum: describe in the FAQ or documentation, how to ask for deletion of all user-related data + install a procedure to execute these requests + give feedback during the process and provide a final confirmation.  
2. Provide an automated procedure (ex. in the account-section - as implemented on GitHub: https://github.com/settings/admin ) for erasure of all data related to a user  

More info on these legal requirements:
- https://gdpr.eu/article-17-right-to-be-forgotten/
- https://gdpr.eu/companies-outside-of-europe/ 

Thanks for looking into this issue, not only for your EU-visitors. This feature is a minimum for a website that records sensitive user-related information.  

As long as this is not resolved, I would advise you on excluding visitors (both citizens and residents) from EU from using your services.

**Comment by Cervator** [comment]
Hey there. Thanks for the perfectly valid bug report and the extra research on legal requirements 👍 

I agree that the current setup is less than ideal. I don't know if there's developer resources available to provide the delete option "the right way" but historically account deletions are handled by emailing the request to support@bountysource.com. That hasn't been well advertised though. I've just added an FAQ entry for it: https://github.com/bountysource/core/wiki/Frequently-Asked-Questions#how-do-i-delete-my-account

That's a stop-gap option at best though, so the request remains valid, and has been for some time - #409 covers it too from a long time ago and I just noticed I even responded there some time ago.

**Comment by johanlives** [comment]
Please email support@bountysource.com for all account deletions.
This is reflected in the FAQ,

**Comment by johanlives** [comment]
> Hey there. Thanks for the perfectly valid bug report and the extra research on legal requirements 👍
> 
> I agree that the current setup is less than ideal. I don't know if there's developer resources available to provide the delete option "the right way" but historically account deletions are handled by emailing the request to [support@bountysource.com](mailto:support@bountysource.com). That hasn't been well advertised though. I've just added an FAQ entry for it: https://github.com/bountysource/core/wiki/Frequently-Asked-Questions#how-do-i-delete-my-account
> 
> That's a stop-gap option at best though, so the request remains valid, and has been for some time - #409 covers it too from a long time ago and I just noticed I even responded there some time ago.

Thanks @Cervator
