### ISSUE TITLE
Stats page doesn't show beyond April 2018

### ISSUE THREAD

**Issue by jpthor** [bountysource/core#1383]
Current: Stats page stoppped recording information in April 2018

Desired: Show to today

https://www.bountysource.com/stats

Code for the particular page: https://github.com/bountysource/core/blob/7c8af782a206caa377e33e0f998ea3357ea0396c/app/assets/javascripts/app/about/stats.js

**Comment by wkonkel** [comment]
To update manually, from a Heroku console run: `PublicStat.update_singleton`

This command should be running every hour according to line 5 of `config/initializers/crontab.rb`. Perhaps there is an error with the Heroku Scheduler?

**Comment by uivlis** [comment]
Hey @wkonkel, are you sure? I tried `bundle exec rails runner "PublicStat.update_singleton"` and this is the output:
```
undefined method `[]' for nil:NilClass
```

**Comment by pierlon** [comment]
@uivlis You can run it via the Rails console: 

```
$ ./bin/rails c
irb (main) > PublicStat.update_singleton
```

**Comment by uivlis** [comment]
Nope, still got it:
```
NoMethodError: undefined method `[]' for nil:NilClass
```

**Comment by pierlon** [comment]
@uivlis could you try again with the changes from my [PR](https://github.com/bountysource/core/pull/1385)?
