### ISSUE TITLE
How to post a bounty with BTC

### ISSUE THREAD

**Issue by XVilka** [bountysource/core#1390]
I am trying to set a bounty to the issue in BTC, but it shows:
```
You'll need metamask switched on to be the first contributor.
```
And it is not mentioned anywhere in the FAQ or help what should be done. Googling didn't help either.
![image](https://user-images.githubusercontent.com/203261/62407696-5d619c00-b5ef-11e9-86ca-86ae05d1d25c.png)

**Comment by XVilka** [comment]
For those who will find this issue - there is an open-source and free of charge alternative, that supports various cryptocurrencies and allows to set bounties on GitHub issues - [jollheef/donate](https://github.com/jollheef/donate).

This is how it looks [in the GitHub issue](https://github.com/jollheef/donate/issues/8)

![image](https://user-images.githubusercontent.com/203261/73710690-a978cf00-473f-11ea-80be-a2e62dad2f27.png)

**Comment by p-m** [comment]
Hi,
It seems, that jollheef/donate does not exist any more. Is there any other solution please for paying with BTC or DASH?
TIA for any hints, Peter
