### ISSUE TITLE
Bountysource is not reading Gitlab Issues correctly

### ISSUE THREAD

**Issue by johanlives** [bountysource/core#1393]
# ISSUE

Bountysource is not parsing Gitlab issues.   Github issues still work correctly but Bountysource is not reading Gitlab issues correctly. 

# REQUIRED

Need someone to get some eyes on this and try to debug & fix the issue so Gitlab bounties can be posted.

**Comment by meelash** [comment]
Can you specify what is incorrect about Gitlab issue parsing? Maybe a screenshot of what is happening? This is what I am getting locally for when I paste this issue into the search: https://gitlab.com/cmdevs/ColonialMarines/issues/7481
![Screen Shot 2019-08-31 at 6 46 19 PM](https://user-images.githubusercontent.com/59001/64069797-c0127b80-cc1f-11e9-92e4-edf0607d611f.png)

**Comment by meelash** [comment]
Is the live version up-to-date with the latest master?

If so, maybe the issue is related to corrupted data. Could possibly be an expired or invalid gitlab access token, although I've seen behavior that makes me doubt that.

**Comment by meelash** [comment]
One general issue I have noticed, is that if the initial parse fails for some reason the corrupt data is stored and now there is no way to update it. Should we be checking for updates on the source site every time the page is loaded to keep it up to date?

**Comment by johanlives** [comment]
Thanks @meelash 
The issue was solved internally and required access to other system.
I appreciate your help and have credited your Bountysource account with token of appreciation
This issue will be closed
