### ISSUE TITLE
Notify user when inactivity fee is debited

### ISSUE THREAD

**Issue by johanlives** [bountysource/core#1394]
# ISSUE

Bountysource charges an inactivity fee on accounts that earn money but do not withdraw after 3 months.

see:  spec/services/charge_user_inactivity_fee_spec.rb

We need to notify users when the fee is charged so they have a chance to log in and claim money before any further fees.

# REQUIRED

Notify user by email when inactivity fee is charged

Get in contact with Johan at support@bountysource.com for more details and message copy.

**Comment by sahalsaad** [comment]
Fixed in #1395 pr.
