### ISSUE TITLE
can't add / verify eth wallet via metamask

### ISSUE THREAD

**Issue by g--o** [bountysource/core#1398]
Gets an error:
`angular.js:9778 Error verifying account Error: [ethjs-query] while formatting inputs '[[{"type":"string","name":"Message","value":"By signing this transaction, I prove my ownership of account undefined"}],null]' for method 'signTypedData' error: Error: [ethjs-format] hex string 'undefined' must be an alphanumeric 42 utf8 byte hex (chars: a-fA-F) string, is 0 bytes`

edit: would also appreciate help here since i can't claim my bounty =(

**Comment by johanlives** [comment]
Duplicate
