### ISSUE TITLE
Fix the Bountsource Github Plugin / Integration Tool

### ISSUE THREAD

**Issue by johanlives** [bountysource/core#1411]
## ISSUE

The Github plugin is currently not working.
Normally available via Home/Tools (https://www.bountysource.com/tools)

## REQUIRED
Needs a fix.

**Comment by alphashuro** [comment]
Hi @johanlives, can you give a bit more detail explaining what you mean by "is currently not working"? The following would be very helpful:
1. What you were trying to do
2. The steps you too
3. What you expected vs what actually happened

I've set up the project locally, run through the code and tested it on my own account and it seems to be working correctly, so I just need to understand the difference between what you did and what I did so I can pin down the issue :)

**Comment by licarijd** [comment]
I've successfully created an account via Github auth, signed out, and signed out again. Integration appears to be working as expected. Has this been resolved?

**Comment by johanlives** [comment]
Hi  there,

We've had some reports that the Github ticket won't get a footer nor the
labels updated for changes on the platform.

I'm glad you've got it running locally.  That could come in handy for some
future bounties.  By the way, do you have experience with Heroku
optimization?

Cheers

Johan

**Comment by johanlives** [comment]
> Hi @johanlives, can you give a bit more detail explaining what you mean by "is currently not working"? The following would be very helpful:
> 
> 1. What you were trying to do
> 2. The steps you too
> 3. What you expected vs what actually happened
> 
> I've set up the project locally, run through the code and tested it on my own account and it seems to be working correctly, so I just need to understand the difference between what you did and what I did so I can pin down the issue :)

There are reports that the Github ticket won't get a footer nor the labels updated for changes on the platform.

**Comment by H05ted** [comment]
Working fine 
![зображення](https://user-images.githubusercontent.com/34539338/73485607-155be000-43ac-11ea-8e1e-9d92e4a4a357.png)

![зображення](https://user-images.githubusercontent.com/34539338/73485682-3de3da00-43ac-11ea-9c5d-398d020fb49f.png)

**Comment by alphashuro** [comment]
@johanlives just reminding you to close this...

**Comment by johanlives** [comment]
Thanks Alpha
