### ISSUE TITLE
API seems to be broken

### ISSUE THREAD

**Issue by jjzmajic** [bountysource/core#1413]
According to the official [spec](https://bountysource.github.io/) `GET /bounties/{id}` is supposed to give information on that specific bounty, but it seem to return 404 regardless of the validity of the id.

```python
import requests

magic_header = {'Accept': 'application/vnd.bountysource+json; version=2'}

# this works
sample = requests.get(
    'https://api.bountysource.com/bounties',
    headers=magic_header,
    params=dict(per_page=1, page=1),
).json()[0]
# this does not
sample_data = requests.get(
    'https://api.bountysource.com/bounties/' + str(sample['id']),
    headers=magic_header,
    params=dict(),
).json()
```
Am I doing something wrong?

**Comment by tuxayo** [comment]
Indeed, badges are broken.

[![Bountysource](
https://api.bountysource.com/badge/issue?issue_id=79559410
)](
https://www.bountysource.com/issues/79559410-thunderbird-68-0
)

**Comment by rbeer** [comment]
That link works for me
![Screenshot_20200212-105509](https://user-images.githubusercontent.com/3411649/74323721-3cd88280-4d86-11ea-955d-bf12fa615179.jpg)

The badge you added here also shows
![Screenshot_20200212-105534](https://user-images.githubusercontent.com/3411649/74323751-49f57180-4d86-11ea-8610-3db328c14bd1.jpg)

**Comment by johanlives** [comment]
> According to the official [spec](https://bountysource.github.io/) `GET /bounties/{id}` is supposed to give information on that specific bounty, but it seem to return 404 regardless of the validity of the id.
> 
> ```python
> import requests
> 
> magic_header = {'Accept': 'application/vnd.bountysource+json; version=2'}
> 
> # this works
> sample = requests.get(
>     'https://api.bountysource.com/bounties',
>     headers=magic_header,
>     params=dict(per_page=1, page=1),
> ).json()[0]
> # this does not
> sample_data = requests.get(
>     'https://api.bountysource.com/bounties/' + str(sample['id']),
>     headers=magic_header,
>     params=dict(),
> ).json()
> ```
> 
> Am I doing something wrong?

Are you still experiencing issues here?

**Comment by jjzmajic** [comment]
`{'error': 'Method not found'}`

With that exact code.

Sorry for the late reply, given my time constraints I had to get another source of bounty data for my paper. I hope you manage to resolve this eventually though, the more options the better!

**Comment by johanlives** [comment]
We've just resolved some issues relating to the recept API breaks and site outages
