### ISSUE TITLE
Tracker has already been taken

### ISSUE THREAD

**Issue by tgiphil** [bountysource/core#1414]
Help! Can this be fixed?

![image](https://user-images.githubusercontent.com/124747/74338016-40ecac00-4d56-11ea-88aa-4deeb9cb0c2f.png)

**Comment by johanlives** [comment]
Hi Phil,

Can you send me an email at support@bountysource.com, thanks 

> Help! Can this be fixed?
> 
> ![image](https://user-images.githubusercontent.com/124747/74338016-40ecac00-4d56-11ea-88aa-4deeb9cb0c2f.png)
