### ISSUE TITLE
Remove Bancor Widget from Navbar

### ISSUE THREAD

**Issue by johanlives** [bountysource/core#1420]
### ISSUE
The "Get CAN" button in the navbar toggles the Bancor widget.
This crypto token standard is deprecated and needs to be removed.

### REQUIRED
-Remove the "Get  CAN" Button &  Bancor Widget from the Navbar
-Remove associated code

![image](https://user-images.githubusercontent.com/32894591/75755721-e655d700-5d7a-11ea-97f3-dd2b17c368d8.png)

**Comment by alphashuro** [comment]
Hey Johan, I've submitted a PR here https://github.com/bountysource/core/pull/1421

**Comment by alphashuro** [comment]
Hey @johanlives is there anything still pending on this issue?

**Comment by johanlives** [comment]
> Hey @johanlives is there anything still pending on this issue?
Closed, you can now claim
