### ISSUE TITLE
Fix the Bountysource staging pipeline on Heroku

### ISSUE THREAD

**Issue by johanlives** [bountysource/core#1430]
## ISSUE
Staging on Heroku is broken
We need to fix the pipeline so issues don't affect production

## REQUIRED
Fix the pipeline on Heroku

**Comment by 444nix** [comment]
Is this open to the public? I'm a devops engineer and would love to work on this. How can I get started?

**Comment by alphashuro** [comment]
Hi @444nix, unfortunately I have already made significant progress on this and it is something only one person can do at a time;
