### ISSUE TITLE
CORS issues, pages are blank

### ISSUE THREAD

**Issue by peey** [bountysource/core#1431]
I tried looking at [this page](https://www.bountysource.com/trackers/68393-habitrpg?utm_source=68393&utm_medium=shield&utm_campaign=TRACKER_BADGE), but I can't

This is what I see in the console

![image](https://user-images.githubusercontent.com/4688870/77430857-d96c5680-6e01-11ea-9190-a3a34f44b668.png)

Text:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.bountysource.com/trackers/68393-habitrpg?include_team=true. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://api.bountysource.com/track/?ip=1&_=1585056582788’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://api.bountysource.com/decide/?verbose=1&version=1&lib=web&token=f9b55dbcc390114a4ed685391a7563e0&ip=1&_=1585056582780’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).

Tried in both firefox and chrome

**Comment by johanlives** [comment]
Hi @peey 
Thanks>
We've just resolved some issues relating to the recent site outages.

**Comment by peey** [comment]
Yep, works now. Thanks!
