### ISSUE TITLE
UX: GitHub outages are not handled to tell the user that it's the cause of the error and 

### ISSUE THREAD

**Issue by tuxayo** [bountysource/core#1432]
I though Bountysource had a issue it itself. So I came here to report to GitHub was broken.

The messages on Bountysource are
```
{"error":"Internal server error."}
```

or
![Screenshot_2020-04-03_00-13-46](https://user-images.githubusercontent.com/2678215/78304914-06c2ae00-7540-11ea-8743-1fbbb49c7113.png)

**Comment by tuxayo** [comment]
The errors were one bounty pages: https://www.bountysource.com/issues/79559410-thunderbird-68-0

**Comment by johanlives** [comment]
Hi @tuxayo 
We've just resolved some issues relating to the recent site outages.
