### ISSUE TITLE
GitHub outage shoudn't break bounty pages not linked to GitHub

### ISSUE THREAD

**Issue by tuxayo** [bountysource/core#1433]
Same errors as in #1432 when going to a bounty linked with a Bugzilla instance: https://www.bountysource.com/issues/90834026-implement-rtx-for-webrtc

**Comment by johanlives** [comment]
Hi @tuxayo 
It was a problem with Bountysource API with underlying backend systems issues.  We've just resolved some issues relating to these outages.

**Comment by tuxayo** [comment]
Thanks a lot :D
