### ISSUE TITLE
Internal server error after Twitter linking cancellation

### ISSUE THREAD

**Issue by AlexWayfer** [bountysource/core#1438]
Hello.

On page from #1437 I'm pressing "Cancel" and getting 500 error:

![image](https://user-images.githubusercontent.com/6510020/78507076-b1c4a900-7786-11ea-9942-682f33052d49.png)

**Comment by johanlives** [comment]
> Hello.
> 
> On page from #1437 I'm pressing "Cancel" and getting 500 error:
> 
> ![image](https://user-images.githubusercontent.com/6510020/78507076-b1c4a900-7786-11ea-9942-682f33052d49.png)

Hi @AlexWayfer 
Yeah, we've had some site issues recently that are now resolved.
