### ISSUE TITLE
Missing ticket history

### ISSUE THREAD

**Issue by tuxayo** [bountysource/core#1445]
Maybe it's a dup of the recent API issues.

example of missing history:
https://www.bountysource.com/issues/1384856-add-support-for-phabricator

Also reproduce on a bunch of bounties from the front page of bountysource

**Comment by brymut** [comment]
Hi, starting to have a look at this today. Will update when I have something.

**Comment by brymut** [comment]
Looks like it was an issue with the `find( :id` parameter used in https://github.com/bountysource/core/blob/82426a75d26fc0a6409eda157562fa2182ce7621/app/controllers/api/v2/timeline_controller.rb#L54
making the method call incorrect, affecting the API then the issue history displayed in the frontend.

Setting up the Pull request.
