### ISSUE TITLE
Fix email notification issues

### ISSUE THREAD

**Issue by johanlives** [bountysource/core#1446]
### ISSUE
Email signup notifications are not being received.
Or, are received after severe delays

This is causing issues with user signups / signins.

### REQUIRED
Investigate & fix

**Comment by rosa2** [comment]
I have had this problem with 2 different emails last 2 days.
Thanks for the tool

**Comment by trialism** [comment]
I'm also having this issue. The email confirmation limit is two hours but the verification emails come 6-10 hours later.

**Comment by LaPeste** [comment]
I created an account today and I have this exact problem.
I asked to resend the verification code 3/4 times today but I have never received a single email.
