### ISSUE TITLE
Bountysource shows open bug as 'closed'

### ISSUE THREAD

**Issue by alexxcons** [bountysource/core#1461]
https://www.bountysource.com/issues/91303660-

I would like to put money on that bug, but it is not possible, since it is shown as 'closed'

If I follow the link "show in bugzilla", the bug clearly is still open (see attached screenshot)

Possibly related to the current general slowness of bountysource.com ?

**Comment by alexxcons** [comment]
![Bildschirmfoto_2020-04-30_10-34-16](https://user-images.githubusercontent.com/2205293/80690059-8e172900-8ace-11ea-93bb-9359a516f5b6.png)

**Comment by johanlives** [comment]
This has been largely been solved.

We also have a new admin tool to force close/open in the event of sync issues in the future to allow users to get on with the claim/bounty process.

For any remaining sync issue, please email support@bountysource.com and we will fix ASAP.

Regards

Johan

**Comment by alexxcons** [comment]
Thanks alot for fixing it !
(xfce just moved to gitlab .. so now the mentioned bug is closed on purpose :) )
