### ISSUE TITLE
BUG - Bounty Checkout Receipt $NaN error

### ISSUE THREAD

**Issue by johanlives** [bountysource/core#1464]
### ISSUE

Bounty Checkout Receipt gives $NaN error

![image](https://user-images.githubusercontent.com/32894591/80938187-8384c880-8e1b-11ea-91f5-7d7f64941758.png)

**Comment by brymut** [comment]
I can check this out over the next couple of days

**Comment by johanlives** [comment]
> I can check this out over the next couple of days

Hey @brymut I put a small  bounty on this, https://www.bountysource.com/issues/91340373-bug-bounty-checkout-receipt-nan-error

**Comment by brymut** [comment]
Thanks @johanlives, seen it.

**Comment by ImUrX** [comment]
Was this fixed or is it still giving out NaN?

**Comment by Amraneze** [comment]
@johanlives, @brymut  was the bug fixed or not yet ?

**Comment by brymut** [comment]
its fixed. @ImUrX @Amraneze

**Comment by ImUrX** [comment]
then the issue needs to be closed for claiming the reward @brymut
