### ISSUE TITLE
BUG - Bounty payments not displayed (for successful payments) 

### ISSUE THREAD

**Issue by johanlives** [bountysource/core#1465]
### ISSUE

**Bounty details are not displayed on issue page:s**.
* Bounty payments
* Bounty amounts
* Backer details

**Payment is successful:**
The payment has been debited from backers Paypal account.
The admin page for the issue has registered as funded

Eg. https://www.bountysource.com/issues/59613396-choose-alternative-download-location-in-settings-external-sd

![image](https://user-images.githubusercontent.com/32894591/80944576-3b6ea180-8e2d-11ea-99a3-b50cd80b81f3.png)

Console logs screenshot might be a red-herring.
Recent PR https://github.com/bountysource/core/pull/1463 addressed some other Paypal issues where bounties were debited but not registered at all.  

These may be related.

### REQUIRED

Identify how the Issue page can fail to display details that are available to the admin page of the same issue?

**Comment by brymut** [comment]
Having a go at this over the week.

**Comment by brymut** [comment]
Hi again @johanlives, I think I've figured out why the backer details aren't being shown, will open PR, however, I can't reproduce the bounty amount issue you mentioned with the link. Is there another issue with the same problem? Or a way I can reproduce it on my own.

**Comment by brymut** [comment]
HI again @johanlives, just wanted to check if this is all sorted?
