### ISSUE TITLE
Investigate API Issues

### ISSUE THREAD

**Issue by johanlives** [bountysource/core#1466]
### ISSUE

There are persistent issues with the Bountysource API.

Eg.
#### 1 - Trying to delete an account in admin
![image](https://user-images.githubusercontent.com/32894591/80945627-8c7f9500-8e2f-11ea-9ee9-96d5709d73c2.png)

#### 2 - Attempting to view an issue in admin
![image](https://user-images.githubusercontent.com/32894591/80945739-d2d4f400-8e2f-11ea-9f85-a011ef02b735.png)

#### 3 - Loading the front page
![image](https://user-images.githubusercontent.com/32894591/80945966-5c84c180-8e30-11ea-92b7-3897cc599260.png)

#### 4- Attempting to update a bounty in admin
![image](https://user-images.githubusercontent.com/32894591/80945913-3b23d580-8e30-11ea-96d3-58948993f71e.png)

####5 - On a slowly loading Issue Page
![image](https://user-images.githubusercontent.com/32894591/80946131-b4232d00-8e30-11ea-9923-3c9427fe43fb.png)

### REQUIRED
Identify the cause of these issues and propose a fix

**Comment by drastik** [comment]
I see CORS errors when trying to create an account also.

**Comment by Azekthi** [comment]
I'm also seeing CORS errors when trying to update my profile. Below is Firefox's console when trying to save my profile:

![image](https://user-images.githubusercontent.com/11371137/81905708-14357400-9593-11ea-9971-ecedaada136d.png)

**Comment by barkovv** [comment]
Same issue when just opening the site. It's unusable.
![image](https://user-images.githubusercontent.com/5094065/91074221-e7d6cc80-e644-11ea-86ab-a6aa4ebbc3e8.png)

**Comment by Mourad-R** [comment]
Fixed
