### ISSUE TITLE
Not clear how to sign up by email

### ISSUE THREAD

**Issue by samtygier** [bountysource/core#1468]
It is not clear how to create a new account with an email address. These is no link or button to create an account on the home page or on the sign in page.

It is possible, just really well hidden.

![Screenshot at 2020-05-05 20-50-20](https://user-images.githubusercontent.com/1113988/81109546-2c155400-8f12-11ea-812d-d76639d2fe60.png)

**Comment by drastik** [comment]
Agreed, that was very unexpected when the form changed after entering an email not in the system.  

Had thought up to that point I was SOL.  You still can't create an account due to CORS errors when returning from email verification [ see: #1466 ]  (email takes roughly 12hrs to send as well).

**Comment by johanlives** [comment]
Email verification process was broken but is largely resolved now along with CORS errors.
Please let us know at support@bountysource.com if this persists for you

**Comment by samtygier** [comment]
There is still no visible way to create an account.

Could you add a "create account" button?
