### ISSUE TITLE
Github issue is displayed as open even though closed

### ISSUE THREAD

**Issue by marcelklehr** [bountysource/core#1474]
https://www.bountysource.com/issues/1692470-add-sharing-use-share-api

The issue has been closed and reopened in the past.

**Comment by johanlives** [comment]
This has been largely been solved.

We also have a new admin tool to force close in the event of sync issues in the future to allow users to get on with the claim process.

For any remaining Github sync issues, please email support@bountysource.com and we will fix ASAP.

Regards

Johan
