### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by DaMatrix** [bountysource/core#1484]
Just tried making some changes to a project configured using GitHub Committer tools, and after hitting save it loads forever. The browser log is showing cross-origin access errors:
![screenshot](https://i.daporkchop.net/95nVg4RY.png)

Possibly related to #1475

**Comment by WhyNotHugo** [comment]
Editing one's profile in https://www.bountysource.com/settings doesn't work either:

![2020-05-30T21:42:21,165979797+02:00](https://user-images.githubusercontent.com/730811/83337810-d718f380-a2ad-11ea-854c-2ad1bfe6b3e3.png)

Reproduced in Firefox on both Linux and iOS.

**Comment by johanlives** [comment]
These have largely been resolved.
Please let us know at support@bountysource.com if you continue to experience issues.
