### ISSUE TITLE
Fix Admin Send Cash Out

### ISSUE THREAD

**Issue by johanlives** [bountysource/core#1486]
### ISSUE

Admin Function broken

Cannot register cashout as Sent in /admin/cash_outs/pending

![image](https://user-images.githubusercontent.com/32894591/82767439-ed1c5380-9e6a-11ea-97d0-8e2c181e9d6f.png)

![image](https://user-images.githubusercontent.com/32894591/82767423-d118b200-9e6a-11ea-8a2f-6dbe4d412598.png)

### REQUIRED

Fix Issue

**Comment by brymut** [comment]
Will have a look, at these issues, they seem related

**Comment by johanlives** [comment]
Resolved

**Comment by brymut** [comment]
@alphashuro Could you please public notify people you're working on something? Feels like I wasted my time.

**Comment by johanlives** [comment]
> @alphashuro Could you please public notify people you're working on something? Feels like I wasted my time.

Hi @brymut 
This was entirely my fault.
I'm sorry I wasted your time.
I'll message you on TG about resolving this with you
