### ISSUE TITLE
Investigate & Fix failing email verification

### ISSUE THREAD

**Issue by dpocock** [bountysource/core#1493]
I received the email containing the verification link

Clicking the link, it takes me to a page with the title "Verifying..." and a progress bar.

The progress bar moves to 100% and it sits on this page without doing anything.

After 5 minutes, I tried clicking "Sign In" and it told me the email address hasn't been verified yet.

**Comment by johanlives** [comment]
I'm putting a bounty on this.

### ISSUE 
There are multiple reports of user unable to sign-up, or reset due to email verification process failing.
This persists and does not seem related to the recent delayed_jobs & DB issues.

### REQUIRED
Investigate fault
Propose / Implement solution

**Comment by johanlives** [comment]
Thanks for the fix @alphashuro.
Test seems to work.

**Comment by johanlives** [comment]
@dpocock 
Can you please retry and confirm?
Thanks
