### ISSUE TITLE
Update FAQ to contain point 2.13 of new Terms of Service

### ISSUE THREAD

**Issue by castilma** [bountysource/core#1497]
Title.

IIUC, if no one succesfully claims a bounty 2 years after it has been posted, the whole money goes to Bountysource.
That's a very important point for users of the platform to know.

IMHO, this will now be a major drawback of Bountysource, as it effectively turns your bounty into a bet against Bountysource, saying, that your issue will be resolved in less than 2 years.

I hope, though, that I just misunderstood that point.

**Comment by Phoenix616** [comment]
I don't think you misunderstood that, it's pretty clearly stated that the money goes to the company if not claimed.

Can't wait how companies [like IBM](https://www.bountysource.com/issues/38471802-update-the-altivec-vsx-to-be-on-par-with-the-other-accelerated-architectures) react to having their money effectively stolen, without even a warning when putting down the money (still says "Expires: Never"). Other platforms like gitcoin.co, freedomsponsors.org or issuehunt.io seem to be handling it by simply returning the bounty (minus any transfer/processing fees and maybe their own cut)

**Comment by ccoenen** [comment]
My interpretation of that point was also the same. I find this outrageous. Doing a thing like that, a cash grab of that magnitude with money that **clearly was intended for something _very_ different**, seems like it should be against the law.

**Comment by johanlives** [comment]
New ToS has been withdrawn. https://github.com/bountysource/core/pull/1498
ToS will be revised and clarified and in the future

**Comment by dreua** [comment]
@ bountysource bosses:
While you're at it, please also consider revising and clarifying point 2.9 of the ToS:
> Bountysource reserves the right to reject, cancel, interrupt, remove, or suspend a Bounty at any time and for any reason. Bountysource is not liable for any damages as a result of any of those actions. Bountysource's policy is not to comment on the reasons for any of those actions.

Do that well with a humble apology and you might be able to regain some of the trust you just lost.
