### ISSUE TITLE
Fix bounty totals that are not displaying correctly

### ISSUE THREAD

**Issue by johanlives** [bountysource/core#1502]
### ISSUE

Bounty totals are not displaying correctly.
Bounties have been received and registered. Backers show correct breakdown.

![image](https://user-images.githubusercontent.com/32894591/85256074-d9363280-b4a6-11ea-8b7f-c10be55e41ef.png)

### REQUIRED
Investigate & Fix

**Comment by gianpaj** [comment]
Does this still need to be worked on?

**Comment by johanlives** [comment]
> Does this still need to be worked on?

Yes
