### ISSUE TITLE
Allow bounties on anything, after the fact [$10]

### ISSUE THREAD

**Issue by jchulce** [bountysource/core#153]
Bountysource is currently setup to set bounties first, then have someone solve the issue. Most of the time, this works well, as people know what they want in a contribution ahead of time. However, this isn't always the case. Sometimes you get really awesome unexpected drive-by contributions, and I'd like to reward people for them. Ideally I'd like to have the ability to assign rewards to anything on github (such as comments, gists, commits, solving bugs, or even just for reporting bugs)
##

**Comment by beroal** [comment]
Rewarding after the fact is a donation. That problem was solved long before Bountysource; there are a lot of donation websites.

**Comment by kaiansaari** [comment]
Closing this issue as this is not planned as part of the roadmap. As mentioned there are donation websites available for this purpose.
