### ISSUE TITLE
What is wrong with your support and cash out process?

### ISSUE THREAD

**Issue by WafflesK** [bountysource/core#1539]
I requested cash out almost a month ago and it's still pending. Your support is ignoring my emails.

You happily take money, take 10% cut on cash out and ignore all cash out requests and emails. What is wrong with you? This is the most garbage service I have ever encountered.

**Comment by aster94** [comment]
Same here

**Comment by Speedwares** [comment]
Same here been messaging support and no one is answering

**Comment by megashub** [comment]
Hell, I can't even reset my password to get logged in. The site doesn't even send the reset email despite saying it found my address. This is nothing more than a cash grab at this point. Avoid at all costs.

**Comment by FrancescoBorzi** [comment]
Same here.

**Comment by Winfidonarleyan** [comment]
Same here :/

**Comment by braewoods** [comment]
Same here. The website is pointless now if there's no way to actually get paid.

**Comment by FrancescoBorzi** [comment]
@NoNonsense126 @wkonkel @alphashuro @hjchan @JalenOng @Mourad-R @KevinSia @BinaryFissionGames @johanlives @brymut can anyone please give an answer to us? why has the support team stopped answering our messages? is Bountysource going bankrupt or just having some issues which will be addressed? At least let us know

**Comment by BinaryFissionGames** [comment]
@FrancescoBorzi I know you just tagged a bunch of contributors to hopefully get some answers from someone who knows, but I just made one pull request back in 2017, I have no idea what's going on with bountysource. 

It was/is a cool idea, but it obviously doesn't work when there is no transparency or support. Back when I made that PR, there was, like, 2 dudes working on it while also working their own jobs, which was not sustainable for them at all. So they had canya.io take over, and they didn't really fix any of the problems, and did stuff like [this](https://blog.elementary.io/goodbye-bountysource-hello-github-sponsors/). 

Now, it looks like bountysource was acquired by [blockchain group](https://www.theblockchain-group.com/)? It feels really bizarre that this project got dragged into the crypto-hellhole, but I guess that's what its about now. Maybe you'd have better luck contacting them with the email on there website, since they proudly display bountysource under their "network of companies". 

It goes without saying, but it's probably a good idea to move away from bountysource, considering the direction it's been heading for years.

**Comment by FrancescoBorzi** [comment]
@BinaryFissionGames thanks for your honest answer, I appreciate it.

**Comment by istnv** [comment]
I've been trying for weeks to get paid a bounty earned in early April (#1538)

**Comment by megashub** [comment]
I contacted the blockchain group and was forwarded to the new director they assigned to run the site: Nicolas le Herissier. His email address is: nleherissier@theblockchain-group.com

here's what I sent: 
Hello,

Please understand I don't say any of this out of malice. Your apparent neglect of bountysource.com has, in effect, meant that people who have contributed bounties cannot access their money, and people who have done the work to satisfy those bounties cannot get their rightful compensation. This feels like fraud. 

And since I've contributed to a bounty that needs to get paid out, have forgotten my password, and cannot reset my password because the site is broken, I am stuck with no help in sight. There are hundreds of such stories around the internet from people all trying to get your attention to help them too. 

So my ask is simple: Make a decision -- 1. Lean in and start running that site properly or 2. Refund all active bounties (according to the site those are all pending bounties 2 years old or younger) and close the site entirely. Don't leave us all hanging with our money tied up in your site. Beyond just being a shitty thing to do to people, it's very likely illegal.

Thank you.


Nicolas responded:
I recently took the lead of Bountysource and we are changing the team and ressources, for better customer experience and ambitions.

We are sorry about late cash out but we will fix it asap. 


My reply:
Thank you for responding and taking steps to correct the situation. I very much appreciate it. Given how long it's been, I think you owe the community a formal statement with clear target dates for resumption of proper support and website operations. 

Would you consider posting something publicly that provides such a timeline and includes a commitment to regular updates going forward, so those of us with money tied up on the service can follow along?



Nicolas's response:
All cashout issues will be solved quickly, and new proceedings will be applied and communicated. Thank you for your help.


This is where I left it. Please post an update if you actually see action from The Blockchain Group...

**Comment by FrancescoBorzi** [comment]
@megashub I can confirm I had a very similar experience as yours (I contacted Nicolas etc...) and, thanks to him, some of our developers started getting their bounties again. I hope they will keep fixing all Bountysource issues!

**Comment by braewoods** [comment]
There's also other issues like just being able to claim bounties in a timely manner. Their system takes forever to notice when an issue has been closed in the upstream repository. It's been over 2 weeks by now for some of my bounties and I still cannot claim them. But the far worse one is just being able to "cash out" as if you can't do that the BountySource funds are effectively equivalent to digital monopoly money -- utterly worthless.

**Comment by megashub** [comment]
Please contact Nicolas and post your experience here for transparency, and to help others to do the same who may find this later. He's committed to addressing cash-outs and claims quickly. So let's hold him accountable to following through on that. 

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by braewoods** [comment]
@megashub But that's the thing. We shouldn't *have* to do this. The cash out process is initiated through their system so they should already have all the information they need to know who is left to be processed.

**Comment by megashub** [comment]
I agree. We shouldn't. But here we are. I can't even reset my password. Their system is borked. I think they're doing it all manually. But who knows. ‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Speedwares** [comment]
It would also be awesome if anyone on here let us all know if they receive theirs. I don't know how long they plan to use to distribute all the pending ones and if it's still being processed on Fridays only.

**Comment by WafflesK** [comment]
Still nothing. ~1.5 months since I asked for cash out...

**Comment by abmyii** [comment]
> Please contact Nicolas and post your experience here for transparency, and to help others to do the same who may find this later. He's committed to addressing cash-outs and claims quickly. So let's hold him accountable to following through on that.

I also sent him an email a week ago with no reply.

**Comment by megashub** [comment]
Best of luck on your cash-out. It's radio silence from blockchaingroup's Bountysource Director Nicolas Le Herissier these days, after committing me in email that his new team will make it all better. 

Here are some email addresses you can try for help:
Xavier Latil: xl@theblockchain-group.com (CEO)
Lia Almeida: lia@theblockchain-group.com (COO)
Nicolas Le Herissier: nleherissier@theblockchain-group.com (Bountysource Director) 
main inbox: hello@theblockchain-group.com

**Comment by abmyii** [comment]
> Here are some email addresses you can try for help:
> Xavier Latil: [xl@theblockchain-group.com](mailto:xl@theblockchain-group.com) (CEO)
> Lia Almeida: [lia@theblockchain-group.com](mailto:lia@theblockchain-group.com) (COO)
> Nicolas Le Herissier: [nleherissier@theblockchain-group.com](mailto:nleherissier@theblockchain-group.com) (Bountysource Director)
> main inbox: [hello@theblockchain-group.com](mailto:hello@theblockchain-group.com)

Thank you for compiling this list of emails!

Also, what rights do bounty posters have in terms of their cash that is being held by BountySource?

**Comment by m3nu** [comment]
> Also, what rights do bounty posters have in terms of their cash that is being held by BountySource?

Chargeback via PayPal should be feasible, if there is no other response. Possible for any donations made over the previous 6 months. Of course, this will create a big chaos if parts are already paid out. So I'll observe for a few more days and start chargebacks next week. Ultimately up to the good folks from TBG on how they want to proceed from here.

**Comment by abmyii** [comment]
> > Also, what rights do bounty posters have in terms of their cash that is being held by BountySource?
> 
> Chargeback/dispute via PayPal. Just open the transaction details page, scroll all the way down and click _Resolution Center_.
> 
> Then wait for a few days for a response. If nothing happens, we escalate it to PayPal. If there is still no response, they generally side with the buyer (bounty poster).

Even after 2 years?

**Comment by m3nu** [comment]
You can claim back payments made in the last 6 months.

**Comment by abmyii** [comment]
> You can claim back payments made in the last 6 months.

There goes $200 I guess - eternally stuck in limbo...

**Comment by jorisgeer** [comment]
I have updated the Wikipedia article to include this issue.

**Comment by m3nu** [comment]
Any movement here? Anyone got payouts? If not, I need to start raising disputes with PayPal now to claw back all donations from the past few months. Very annoying.

**Comment by FrancescoBorzi** [comment]
> Any movement here? Anyone got payouts? If not, I need to start raising disputes with PayPal now to claw back all donations from the past few months. Very annoying.

I can confirm that I got answers from Nicolas Le Herissier: nleherissier@theblockchain-group.com

I suggest to send him an email before starting the disputes

**Comment by abmyii** [comment]
> > 
> 
> I can confirm that I got answers from Nicolas Le Herissier: [nleherissier@theblockchain-group.com](mailto:nleherissier@theblockchain-group.com)
> 
> I suggest to send him an email before starting the disputes

Not so for me...

**Comment by remyabel** [comment]
He responds but still hasn't processed my payout (it's been a month).

**Comment by m3nu** [comment]
I'm talking to Xavier Latil on Linkedin. He's also referring to Nicolas le Herissier, the new Bountysource CEO. I've dropped them and email and CCed @ThomasWaldmann.

Until they can resolve it, I've raised a dispute and the case is already with PayPal due to be decided within the next days. Once that's through, I'll do any overdue payments related to the [Borg](https://github.com/borgbackup/borg) project directly via PayPal.

**Comment by m3nu** [comment]
Got a promising response today saying they processed most pending payouts.

If not, please submit your registered email for checking to `rebecca [ at ] theblockchain-group.com` and CC myself at `hello [at] borgbase.com`, so I also see what's going on until all works normally again.

@remyabel @abmyii @megashub @ThomasWaldmann

**Comment by abmyii** [comment]
> If you're still waiting, please submit your registered email for checking to `rebecca [ at ] theblockchain-group.com` and CC myself at `hello [at] borgbase.com`, so I also see what's going on until all works normally again.

Done, thank you very much for your efforts.

**Comment by remyabel** [comment]
Also sent an e-mail.

**Comment by istnv** [comment]
Sent emails (again). I have never had a response from either Nicholas or Rebecca.

**Comment by remyabel** [comment]
Cool I *finally* got paid. Thank you @m3nu for your persistence.

**Comment by m3nu** [comment]
Great, how about you, @ThomasWaldmann? Since I need to close the disputes against them if they are cooperating.

**Comment by remyabel** [comment]
I can't even log into bountysource anymore, I get an internal server error. Not worth the pain, honestly.

**Comment by m3nu** [comment]
Logging in works as of now. What are good alternatives that allow linking a Github issue to 💰?

**Comment by WafflesK** [comment]
"Processed most payments" huh, sounds like bs to me. Mine is still pending.

Sent an email, let's see if they will answer.

**Comment by abmyii** [comment]
Hang in there @WafflesK - it took over two months and some persistence, but I also received my bounty. Thank you again @m3nu for your efforts!

**Comment by WafflesK** [comment]
It took about a week of waiting, but I've got my money today. Huge thanks to @m3nu!

**Comment by ThomasWaldmann** [comment]
<img width="796" alt="Screenshot 2021-08-21 at 15 17 54" src="https://user-images.githubusercontent.com/356103/130323078-cd0fe151-8d31-4be9-b24c-d602137cb335.png">

I also checked my paypal account - no related payment received from BS.

@WafflesK can you reopen?

**Comment by m3nu** [comment]
Please check your emails, @ThomasWaldmann. There is a lady, Rebecca, who is in charge of payouts. I brought up your case in late July, but you didn't send her the details yet. I've replied again just now. Please answer there. She will ask you some questions and then process it. Same as with the others.

**Comment by aster94** [comment]
I have sent email both to the bounty source support and to Nikolas but I still haven't received the money from a bounty which I would like to delete

https://www.bountysource.com/issues/98272677-cbi-compatibility

**Comment by connortechnology** [comment]
I have emailed them as well regarding my payout, which has also not happened.  
I too am not able to login, using the github authentication method.
Our team ZoneMinder has a lot of posted bounties, so it is a real shame that they are non functional.

**Comment by m3nu** [comment]
Payouts are still happening. Someone confirmed a payout to me just this morning after emailing Rebecca.

**Comment by ghost** [comment]
Same they're back to delays. I cashed out on Sept 9 and sent an email on Wednesday with no response. Not looking good.

**Comment by Sl1mb0** [comment]
Why has this issue been closed if people are still not receiving payouts?

I cashed out a couple weeks ago, and still haven't heard anything.

**Comment by ThomasWaldmann** [comment]
@WafflesK please reopen, it still affects other people.

**Comment by connortechnology** [comment]
Have emailed everyone again.  Will be warning our supporters to stay away from bountysource.

**Comment by sonninnos** [comment]
Is the plug finally pulled then..? No mercy for these scheisters.

**Comment by davidebeatrici** [comment]
mumble-voip/mumble#5403

**Comment by davidebeatrici** [comment]
Looks like the website is back online, but no feedback from the company whatsoever about what happened?

**Comment by bountysource-support** [comment]
Hello all, we set a new team with a new back office. 

Cashout and support issues are fixed faster than before, don't hesitate to contact the mail support « support@bountysource.zendesk.com » if you need any help.

**Comment by ghost** [comment]
Are you really processing cash outs? I've been waiting 16 days for mine to process.

**Comment by ThomasWaldmann** [comment]
I have still months old stuff in "pending" status (and just added another payout request).

**Comment by amaitland** [comment]
I've been waiting 3 months also.

@bountysource-support Can you please proactively process all pending payouts. Not just the people who email you.

**Comment by ghost** [comment]
Yea, we shouldn't have to write an email reminder for something you already should have been notified about by your automated system.

**Comment by bountysource-support** [comment]
All the cash out requests are being processed and fastened. 
Sorry for the delay, thanks for your understanding. 
Don't hesitate to contact the mail support « support@bountysource.zendesk.com » if you need any help.

**Comment by ghost** [comment]
> All the cash out requests are being processed and fastened.

So why are many of us still waiting? Are you backlogged or something? Some honesty about the current situation would go a long way. So far all you've given us are some vague reassurances which does nothing to explain why the problem persists.

**Comment by ThomasWaldmann** [comment]
Cash-Out from July 2021 still pending for me (and also some more after that).

Update: that one was paid out meanwhile. But now having a more recent one pending...

**Comment by bountysource-support** [comment]
Hello,

Our cash out process is being improved to be faster and more efficient. Everyone will be paid the amount they are due, however if you have been waiting long or are in a hurry to get the money transferred, please do not hesitate to contact             
« support@bountysource.zendesk.com » or to send us your email address so we can track your cash out. 

If you have any feedback do not hesitate to share it with us. 

Thank you for your patience.

**Comment by jorickert** [comment]
My Cashout from mid April is still pending and nobody responds to my emails about it

**Comment by davidebeatrici** [comment]
![](https://github.com/bountysource/core/assets/5897523/1adc7001-fd4c-42f9-9d5f-eaac26776f9b)

**Comment by theoryshaw** [comment]
The following bounty was completed 6 months ago, still no payout. Was up to $3500, with 24 contributors. 
I would suggest ripping the band-aid off, and declaring bankruptcy on your ponzi scheme. 

https://app.bountysource.com/issues/95048565-make-construction-drawing-generation-like-really-really-awesome

**Comment by Cwpute** [comment]
Currently in a similar situation regarding bounty money i promised, but wanted to withdraw realizing all too late in which situation Bountysource was. Not much money involved fortunately.
I did get a very vague answer:

> Hi Obigre,
Thank you for reaching out.
I will see with the financial team what can be done. I should get an answer by the end of the week.
Kind regards,
Team Support

This was April 11th 2023. I did send a second email the May 22nd with no reply, and just sent a third mail. Now knowing people have been waiting for bounty cashouts for MONTHS, i must admit i don't have much hope getting any money back...

**Comment by Cwpute** [comment]
> The following bounty was completed 6 months ago, still no payout. Was up to $3500, with 24 contributors. I would suggest ripping the band-aid off, and declaring bankruptcy on your ponzi scheme.
> 
> https://app.bountysource.com/issues/95048565-make-construction-drawing-generation-like-really-really-awesome

It currently shows PAID OUT and the bounty value is 0, has your issue been solved @theoryshaw  ?

**Comment by theoryshaw** [comment]
No. They're caught in a ponzi scheme, guaranteed.

**Comment by ghost** [comment]
Paid out just means the funds become available for a cash out by the bounty hunter. The problem is with the cash out process not being fulfilled at all or in a timely manner. It's the main reason I stopped doing any bounties from here as it's all monopoly money if you can't consistently cash out.

**Comment by rugk** [comment]
Wow https://app.bountysource.com/ is really even down right now… https://downforeveryoneorjustme.com/app.bountysource.com?proto=https
