### ISSUE TITLE
Internal server error when signing in using GitHub Account

### ISSUE THREAD

**Issue by mar-v-in** [bountysource/core#1546]
I'm seeing the following response (on https://api.bountysource.com/auth/github/callback?code=XXX&state=YYY) when trying to sign in using mit GitHub account, which I used as a login method to my existing Bountysource account.

```json
{"error":"Internal server error."}
```

Additionally, I can't use the "forgot password" feature with my registered e-mail address (it doesn't send the email), probably because I never had a password set (as I was using sign-in via GitHub).

**Comment by jakub-trzebiatowski** [comment]
Same here. Is it just us two, or is signing in to Bountysource not possible for GitHub-authenticated accounts? It may be a critical issue!

@alphashuro @Mourad-R Could you please take a quick look? I'd love to top-up a bounty, and I can't do that, because I'm not able to sign in...

**Comment by alphashuro** [comment]
Thank you for raising this, I'll take a look later today

**Comment by epoberezkin** [comment]
It is still not resolved...

**Comment by Silver-Streak** [comment]
I can confirm I'm getting this too. Which is especially worrying as today was supposed to be a payout day, and yet nothing has gone to my balances.

**Comment by ale5000-git** [comment]
@mar-v-in: I get the same error but "forgot password" worked for me.
Still I can't associate repositories to Bountysource.

**Comment by shanteadam** [comment]
I can confirm that this error still happens. I tried to sign up to bountysource today using my github account and received the same error. This doesn't leave a great first impression about contributing to bounties using this site.

**Comment by Silver-Streak** [comment]
> I can confirm that this error still happens. I tried to sign up to bountysource today using my github account and received the same error. This doesn't leave a great first impression about contributing to bounties using this site.

I apparently still had a machine with a valid cookie signed in, I was able to log in and set a normal password, so now I can log in without github. 

You might be able to get it to work with forgot password as an option, like mentioned above.

However, I also have now been waiting with 2 payouts in "Processing" for 2 weeks now. I'd be hesitant to post any new bounties on this system until we see some movement happen on both the login and payout items.

**Comment by mar-v-in** [comment]
- GitHub login is still broken for me
- Password reset seems to work again and allowed me to sign in
- I have a cash out pending since Aug 22. They are supposed to run each Friday...
![image](https://user-images.githubusercontent.com/994036/134799693-a586389e-007d-4c91-964f-42ee718fa72d.png)

**Comment by istnv** [comment]
Still broken and I can't find a password reset option.

**Comment by niberius** [comment]
Is this project active? I mean the [BountySource](https://www.bountysource.com/) service.
- I can't log in using GitHub due to the error
- I can't log in using e-mail address. I registered with my email but I don't see the activation email in my mailbox. Even after I clicked `Resend Confirmation Email`. I also checked the Spam folder, there's nothing there from Bountysource
- I haven't tried log in via Twitter or Facebook

**Comment by giraffekey** [comment]
I also get this.

**Comment by TranceLove** [comment]
Same here.

**Comment by Virusmater** [comment]
Should we put bounty on fixing this issue? Oh wait, I cannot login to do this!

**Comment by ale5000-git** [comment]
@mar-v-in: Have you retried recently?

**Comment by ale5000-git** [comment]
It works for me now.

**Comment by mar-v-in** [comment]
Indeed, GitHub login seems to work again. I am still waiting for a cashout, but that's a different issue. Closing this one.

**Comment by eried** [comment]
This is broken again

**Comment by darkyelox** [comment]
I'm having problems with this
