### ISSUE TITLE
Time to leave Bounty Source

### ISSUE THREAD

**Issue by ghost** [bountysource/core#1560]
Bounty Source has stopped issuing timely payouts to bounty hunters and if we're lucky we might get them if we beg for them. There's also unresolved technical issues that cause issues with filing a claim for a bounty even after the original issue has been closed.

All I've seen them do is issue some reassurances that do nothing to solve our problems. I cannot for the life of me see them taking responsibility for the current state of affairs so I believe our only recourse is to leave Bounty Source entirely.

They've taken enough of our time and money and we need a more reliable platform or model for getting paid.

See #1539 and other issues for this trend over the last year.

**Comment by Eldeloro1** [comment]
> Bounty Source has stopped issuing timely payouts to bounty hunters and if we're lucky we might get them if we beg for them. There's also unresolved technical issues that cause issues with filing a claim for a bounty even after the original issue has been closed.
> 
> All I've seen them do is issue some reassurances that do nothing to solve our problems. I cannot for the life of me see them taking responsibility for the current state of affairs so I believe our only recourse is to leave Bounty Source entirely.
> 
> They've taken enough of our time and money and we need a more reliable platform or model for getting paid.
> 
> See #1539 and other issues for this trend over the last year.
