### ISSUE TITLE
Project Logos - Too Big @ a Window Width of 768px

### ISSUE THREAD

**Issue by zachgersh** [bountysource/core#281]
See a perfect example below:

On Mobile sizes we need to drop this logo down a couple of sizes!

![screen shot 2013-10-16 at 1 09 29 pm](https://f.cloud.github.com/assets/689411/1346411/1a0c07e0-369f-11e3-935e-4e116b27ed99.png)
##

**Comment by rappo** [comment]
tracker pages are no longer used (or used rarely and should be phased out...)
