### ISSUE TITLE
Can't Delete Fundraising Projects or Rewards

### ISSUE THREAD

**Issue by awatson1978** [bountysource/core#289]
CRUD/ActiveRecord isn't completed, and users can't delete Fundraisers or Fundraiser rewards.  :(

A bit of feedback as a new user:
It's not clear that Publishing a Fundraiser is going to lock editing of Reward Levels.  Particularly when it's possible to edit the rest of the Fundraiser details.  Also, if something is borked in the fundraiser, there's no option to depublish or delete the Fundraiser.  

Otherwise, fantastic site!

**Comment by rappo** [comment]
We've opted to phase out Fundraisers entirely in favor of [Salt](https://salt.bountysource.com/).
