### ISSUE TITLE
The "Search" of issue is not working correctly

### ISSUE THREAD

**Issue by dacap** [bountysource/core#511]
In [this project](https://www.bountysource.com/trackers/396709-aseprite) you can try to find for "test wacom" and you will not find any issue with that title when there is [one](https://www.bountysource.com/issues/1454788-test-wacom-pen-performance-on-windows). Also the issue must match exact words, that is not user-friendly. (E.g. if I use "mous" and features with "mouse" are not found.)
##

**Comment by iHateInventNames** [comment]
Can't find [this ](https://github.com/minetest/minetest/issues/4153#issuecomment-222284469 )issue [here](https://www.bountysource.com/teams/minetest/issues). Age of the issue is six days

**Comment by niedzielski** [comment]
As a workaround, you an create a Bountysource link to a GitHub issue from their homepage under "Paste any URL to post a bounty."

**Comment by baordog** [comment]
This appears to be totally broken now. The above queries now return 0 results. Search returns 0 results for most queries.

**Comment by Zach443** [comment]
Can confirm. I can't even really use the site because I can't find any issues that have bounties. Everything I search nothing comes up. I set the price ranges from 0-10k and a language like Java or whatever I feel like. Any search term, including leaving that field blank returns nothing.

**Comment by rappo** [comment]
I think this issue has been resolved now. Please re-open with details if that's not the case. thanks!
