### ISSUE TITLE
it's very hard to create a fundraiser

### ISSUE THREAD

**Issue by Nowaker** [bountysource/core#514]
After I signed in, it took me a few minutes of clicking after I found a place where I could add a new fundraiser.

I just deployed the frontend on my localhost, wanted to tune something, and... I'm not able to find a place where I create a fundraiser at all. I had to find an URL in my history, /fundraisers/new, and go directly there. ;)

**Comment by rappo** [comment]
We've opted to phase out Fundraisers entirely in favor of [Salt](https://salt.bountysource.com/).
