### ISSUE TITLE
preview link for non-published fundraisers

### ISSUE THREAD

**Issue by Nowaker** [bountysource/core#519]
I'd want to share my draft fundraiser with my friends by providing them with a link, e.g. /fundraisers/666/lZjznhKoVq2hnRwQpJMO. It's nice to get a fundraiser peer-reviewed before posting.

Yes, I know I may deploy my staging application somewhere and provide my friends with a link to it. ;)

**Comment by rappo** [comment]
We've opted to phase out Fundraisers entirely in favor of [Salt](https://salt.bountysource.com/).
