### ISSUE TITLE
The team settings page is accessible by anyone

### ISSUE THREAD

**Issue by juliangiuca** [bountysource/core#758]
#### Steps to reproduce
- Log in
- Visit  https://staging.bountysource.com/teams/test-satishb3/settings 
#### What it should be
- Only authorized people can see the team settings page.
#### Priority

Low. Everything on that page is publicly visible elsewhere, and an unauthorized person can not edit the content
##

**Comment by hjchan** [comment]
Setting page now unable to view if you are not a member.
