### ISSUE TITLE
Add support for Euros.

### ISSUE THREAD

**Issue by Mikaela** [bountysource/core#858]
I didn't see this in the "payments" tags.

I use euros and understand them better than USD or any other currency. Euro is also one of the most used currencies, so why you don't support it?

The currency list gives me only the following:
- US Dollars ($)
- Bitcoin (฿)
- Ripple (XRP)
- Mastercoin (MSC)

From these I only recognize $ and ฿, but I don't understand them so well.
##

**Comment by HLFH** [comment]
+1 BTC, XRP, MSC are currencies for crooks. Please support € EUR.

**Comment by tuxayo** [comment]
> BTC, XRP, MSC are currencies for crooks.

Or for people that don't have USD and get charged 1€ per payment in dollar(which makes it unusable small monthly payments)

**Comment by ggrandes** [comment]
+1 to EUR

**Comment by HLFH** [comment]
@tuxayo Lool. There are fees when you convert your EUR currency to some cryptocurrency. You're French. Me too. You have [Compte Nickel](https://compte-nickel.fr/). Also, the German Number26 is right now no longer available for new French consumers but maybe in less than a month, they'll say us "hello" again. There is also [Revolut](https://revolut.com/) in UK. So make your choice. I'm using Compte Nickel but I believe that Number26 is the best for this moment. In these three cases, you don't get charged when you expend in foreign currency. It's smoother that way IMHO.

**Comment by tuxayo** [comment]
> There are fees when you convert your EUR currency to some cryptocurrency.

Right but not a crazy 1€/transaction fee.

Thanks for the advice, changing bank would indeed be useful to avoid such inconvenient fees for donations.

**Comment by rappo** [comment]
We've removed the front end currency switcher, as it was giving the wrong impression -- everything is handled as USD. You can still use non-USD through paypal, stripe, btc, etc but it will be converted to USD and shown as such on the front end.
