### ISSUE TITLE
Denominate BTC Bounties in Bits (µ฿, or simply µ) [$50]

### ISSUE THREAD

**Issue by martindale** [bountysource/core#863]
Rather than use the increasingly expensive whole Bitcoin for denomination of [generally] smaller amounts, Bountysource should use the "bits" unit, which allows for two decimal places.  1 Bitcoin is 1,000,000 bits, and a bit is 100 satoshi.

See [the official @bitpay statement](http://blog.bitpay.com/2014/05/02/bitpay-bitcoin-and-where-to-put-that-decimal-point.html) for some further reasoning here.
##

**Comment by johanlives** [comment]
BTC bounties disabled long ago

**Comment by martindale** [comment]
> BTC bounties disabled long ago

Why?
