### ISSUE TITLE
Sign in from GitHub fails on Firefox 20.0

### ISSUE THREAD

**Issue by rappo** [bountysource/core#904]
Firefox 20.0 on Ubuntu. Fails to get redirected back to Bountysource.com
##

**Comment by fedelibre** [comment]
I can confirm the problem. When I try to sign up using my github account, I get redirected to the regular sign in (with email) page.

iceweasel (firefox) 36.0a2
chromium 39

**Comment by rappo** [comment]
@fedelibre Is this for a first time sign up, or subsequent sign ins? For the first time sign up you do need to complete your user profile after coming back from GitHub. For example, adding an email is required for a Bountysource account but not all GH accounts have a public email.

**Comment by fedelibre** [comment]
@rappo Well, I see now: it works but I didn't expect to have to enter an email. Now I understand why.
The first time I tried I saw the page where I must allow bountysource to access the github account. In fact, after entring the email, I see that my github account appears in the bountysource account.

Maybe a warning would help:

> Please enter your email because the email in your github account is not public

**Comment by rappo** [comment]
Closing this... we're up to Firefox 53 now. No reason to care about a potential issue with such an old release.
