### ISSUE TITLE
Add native Bitcoin support [$7]

### ISSUE THREAD

**Issue by 21xhipster** [bountysource/core#926]
Now bitcoins converted to usd after sending.
I prefer keep bounties in bitcoins.
Moreover - for open organisation is critical to have address for auditing there funds goes.
So this bitcoins could be keeping at this address and team could control their funds.
Multisig could be implemented to provide escrow service from bountysource side. That could be good source of monetisation.

**Comment by szhongben** [comment]
Synapsi.com enables you to get paid out in bitcoin from multi-sig escrow.

**Comment by rappo** [comment]
@21xhipster We don't plan to add native Bitcoin support. It would be both an accounting/bookkeeping nightmare for us, as well as confusing to end users as there would be two currencies (and fluctuations in exchange rates). All bounties on this issue have been refunded.
