### ISSUE TITLE
Open-source Community Rights: Should Bountysource allow committers to delist their projects?

### ISSUE THREAD

**Issue by rappo** [bountysource/core#930]
Recently, the question has come up regarding what we should do when an open-source project does not want to allow community members to post bounties on their issues. This is, no doubt, in direct response to the recent discussion on [Hacker News about tip4commit](https://news.ycombinator.com/item?id=8542969).

We do our best to accommodate any request, so the initial thought was to remove the projects from our website as requested. This would be the quickest and easiest resolution. However, this immediately led to an internal debate regarding a community’s rights, and we’re now looking for more input.
## Bountysource’s goals.

We built [Bountysource](https://www.bountysource.com/) to give more people the ability to improve open-source software. There’s a direct need we’re addressing by providing open-source developers new ways to be self-sustaining. Typically, development sponsorship comes from full-time employment at tech companies, one-off contract work, or “donated” time as a hobby. Additionally, we’re giving an outlet to those who otherwise would not contribute.

We consolidate data around open projects into one organized place. Currently, we sync issues from any public repository we support (GitHub, Jira, Trac, Bugzilla, Google Code, Pivotal, and Launchpad), with the aim being to support _all_ open-source projects.
## The challenges of removing a project.

Removing a project on Bountysource is incredibly complicated, and not in a technical sense. 

> “Your right to swing your arms ends just where the other man's nose begins.”
> Zechariah Chafee, free-speech advocate

For every bounty, there are multiple parties involved and each has different concerns.

**Project owners:** Project owners work extremely hard to manage all aspects of their project (branding, code quality, support, legal, etc) and are expected to establish the culture of their community. Some projects fear the introduction of money will transform the community in ways they do not want.

**Developers earning a bounty:** Developers can already submit code to projects, regardless of their motivation. The code itself must stand up to the quality requirements set by the project owners. It shouldn’t matter if the accepted code happens to satisfy the need of others who are willing to pay.

**Backers creating a bounty:** Backers rely on Bountysource to have a comprehensive listing of open-source projects and, if we don’t, ask us to add their favorite project. Bounties provide a way for more users (both technical and non-technical) to contribute to projects.
## Bounties don’t need the core team to be effective.

While many bounties are earned by the core project team, that’s not a requirement. The project should review all code submissions based on quality alone. It doesn’t matter if the motivation for the code was because the developer needed to do the work anyway, was bored on a rainy day, is paid full time by Google, or did it because of a community-driven bounty.
## What happens if we remove projects?

Delisting a project on Bountysource does not prevent users from offering bounties through forums posts, Twitter, and GitHub comments -- but it does remove a proven community tool. If the people want it, they will find a way.
## What happens if we don’t remove projects?

If we refuse to remove projects, we stand to upset any developer that requests their project be removed. We love open-source -- we don’t want there to be animosity directed at us.

**Comment by beroal** [comment]
As a part of the community, I think that delisting is against my rights. (Example. A project is published under a libre license. We have the right to change the source code, to become developers ourselves, or to hire another developer. Bountysource is just supporting this right. Delisting means that the developer allows

* to change the source code
* but not to change the source code for money/with the help of Bountysource.

This sounds like a weird restriction, like that the developer is trying to forbid us to use money/Bountysource.) For example, what should we do if a developer refuses to work on his or her project?
