### ISSUE TITLE
Filters on the Activity>Bounties page

### ISSUE THREAD

**Issue by xan2622** [bountysource/core#942]
Please add filters (checkboxes) to the Activity>Bounties page:
https://www.bountysource.com/activity/bounties

This could help the user see only the Open bounties, or only the Paid ones, refunded ones, etc..
By default, all checkboxes would be enabled, showing everything.

![screenshot001](https://cloud.githubusercontent.com/assets/1732773/5746178/3912a13a-9c2e-11e4-9205-246e842fc1a8.png)
##

**Comment by hjchan** [comment]
The issues are able to filter by open, closed and paid now. Thus closing this.
