### ISSUE TITLE
Change the CSS color for the "Paid Out" tag on the Activity>Bounties page

### ISSUE THREAD

**Issue by xan2622** [bountysource/core#943]
Please change the CSS color for the "Paid Out" tag on the Activity>Bounties page.
Green is already used for "Open".

![screenshot003](https://cloud.githubusercontent.com/assets/1732773/5746360/5cbec892-9c2f-11e4-84bd-af31ea6b0d8d.png)
##

**Comment by x-a-n-a-x** [comment]
How long will we have to wait for you to fix a single line (a single value) of CSS ? :-/

**Comment by hjchan** [comment]
The frontend has revamped.
