### ISSUE TITLE
Some GitHub trackers not showing up in search results on teams/x/projects/manage

### ISSUE THREAD

**Issue by velnias75** [bountysource/core#948]
I've tried anything, googled it, but I simply just can't add
- https://github.com/velnias75/NetMauMau/issues
- https://github.com/velnias75/NetMauMau-Qt-Client/issues

to my team: https://www.bountysource.com/teams/netmaumau/projects/manage

I get a list with proposals if I start typing, but simply not **my** projects. Either I have lost any brain capacity and simply don't understand it, I misunderstand something totally or it is a bug.
##

**Comment by iBeliever** [comment]
I'm facing the same problem. I'll comment back here if I figure it out

**Comment by rappo** [comment]
@velnias75 Looks like the search results aren't returning anything that useful.. I'll leave this issue open until we resolve the underlying issue. In the meantime, I manually added those trackers to your team.

**Comment by velnias75** [comment]
@rappo Thanks, now my issues show up :smile_cat:

**Comment by tchoulihan** [comment]
Same problem here. My projects not showing up

**Comment by lillian-lemmer** [comment]
same issue

**Comment by svnpenn** [comment]
:+1:

**Comment by svnpenn** [comment]
https://github.com/bountysource/core/issues/962

**Comment by svnpenn** [comment]
https://github.com/bountysource/core/issues/986

**Comment by svnpenn** [comment]
:+1:

**Comment by svnpenn** [comment]
@rappo any updates?

**Comment by svnpenn** [comment]
@rappo @wkonkel any comments? This breaks the site for me, as I cannot add any of my own repos to my own team

**Comment by hjchan** [comment]
I believe this issue has been solved now.
