### ISSUE TITLE
My project does not show up in bountysource search.

### ISSUE THREAD

**Issue by ZaneDubya** [bountysource/core#962]
Project is zanedubya/ultimaxna
Link: https://github.com/ZaneDubya/UltimaXNA

There are two bounties assigned to this project, but I can't get them to show up. Typing zanedubya or ultimaxna into search comes up with "no projects found" and "no issues found". I would prefer that the project be named (in bountysource) UltimaXNA, but I can't find an interface to do that.
##

**Comment by svnpenn** [comment]
https://github.com/bountysource/core/issues/948

**Comment by svnpenn** [comment]
https://github.com/bountysource/core/issues/986

**Comment by xloem** [comment]
I've posted some bounties on https://www.bountysource.com/teams/hypercore but if 'hypercore' is typed into the search box, there are no results.

I'm adding this issue to my personal list of issues to add bounties to.  Just $5 for now.

**Comment by kaiansaari** [comment]
@xloem when I search 'hypercore' in /bounties/search? one bounty shows up. Could you tell me how to reproduce?

**Comment by xloem** [comment]
@kaiansaari If I enter 'hypercore' in the search on the top of the front page, I am directed to https://www.bountysource.com/search?query=hypercore , which shows no results.  Is this correct?

**Comment by kaiansaari** [comment]
Thanks @xloem we are aware of the issue and are working on a fix. Many thanks!

**Comment by xloem** [comment]
This bug appears fixed on the live site!  Thanks so much, guys !  Seems this issue could be closed.

**Comment by kaiansaari** [comment]
Thanks @xloem we believe the search issues have now been resolved. A few minor usability improvements planned as well. Thanks again for reporting.
