### ISSUE TITLE
The second B in Bitbucket must not be capitalized

### ISSUE THREAD

**Issue by kazssym** [bountysource/core#967]
Bitbucket is not BitBucket as Boutysource is not BountySource.

**Comment by rappo** [comment]
Can you show me where you see it formatted incorrectly?

**Comment by kazssym** [comment]
I see it on https://www.bountysource.com/trackers/17376148-kazssym-bitbucket-hook-servlet as 'View on BitBucket'.

**Comment by seanders** [comment]
Thank you!

**Comment by rappo** [comment]
Whoa, GitHub reply by email screwed up... no idea why it replied as @seanders !
