### ISSUE TITLE
Badge images have broken, return HTTP 500 

### ISSUE THREAD

**Issue by rtyley** [bountysource/core#980]
On http://blog.bountysource.com/post/87257081709/bountysource-badges :
![image](https://cloud.githubusercontent.com/assets/52038/10728604/29aee3ba-7bdb-11e5-89f2-8421ac4ec332.png)

On https://rtyley.github.io/bfg-repo-cleaner/ :
![image](https://cloud.githubusercontent.com/assets/52038/10728610/34660950-7bdb-11e5-936f-a836a1443274.png)

The image on that page is https://www.bountysource.com/badge/team?team_id=28704&style=raised :
![image](https://cloud.githubusercontent.com/assets/52038/10728640/5dbe9efc-7bdb-11e5-9f09-8c662e6784d8.png)

All these images worked at one point! Is there any updated doc on the badges, if there urls have changed?

**Comment by rappo** [comment]
@rtyley this should be resolved now, I checked on your examples and they look good.
