### ISSUE TITLE
Email page empty

### ISSUE THREAD

**Issue by antosha4e** [bountysource/core#985]
This page has JS errors

https://www.bountysource.com/settings/email

Error 1 :
Error: [ng:areq] http://errors.angularjs.org/1.2.16/ng/areq?p0=SettingsEmail&p1=not%20aNaNunction%2C%20got%20undefined

Error 2 :

Failed to load resource: the server responded with a status of 404 (Not Found)
##

**Comment by lukespragg** [comment]
Old issue, but just noticed this today. https://gyazo.com/2675477e1518a2444397f5c267d78db7.png

**Comment by juanj** [comment]
It appears to me that should be a file named `email.html` in https://github.com/bountysource/core/tree/master/app/assets/javascripts/app/settings but there is not. 
Also it don't appears anywhere in this repository, so I suppose that file get deleted at some point before the project was moved to GitHub.
If this tab was for editing your email, it's not longer needed. You can edit your email from the profile tab.
