### ISSUE TITLE
Issue tracker not showing up?

### ISSUE THREAD

**Issue by lily-seabreeze** [bountysource/core#986]
I can see the issue tracker here: https://www.bountysource.com/trackers/7646105-hypatia-engine-hypatia

But I cannot add this project's issue tracker to my team.
##

**Comment by svnpenn** [comment]
:+1:

**Comment by svnpenn** [comment]
https://github.com/bountysource/core/issues/948

**Comment by svnpenn** [comment]
https://github.com/bountysource/core/issues/962

**Comment by rappo** [comment]
closing, dupe of https://github.com/bountysource/core/issues/948
