### ISSUE TITLE
Broken unsubscribe link

### ISSUE THREAD

**Issue by orschiro** [bountysource/core#989]
Dear all, 

Just received a broken email unsubscribe link:

![image](https://cloud.githubusercontent.com/assets/170947/11323056/2006bc84-9107-11e5-9142-c8097faf4c7a.png)

The link of the unsubscribe button is:

```
http://notifications/unsubscribe?email=person%3A59705dfc3e%3A24589&type=bounty_alerts_tracker_1006732
```

Warmly,

~ Robert

**Comment by wkonkel** [comment]
This is now fixed for new emails.

To unsubscribe from an existing email that has this issue, replace the ```http://notifications/unsubscribe``` portion of the unsubscribe URL with ```https://www.bountysource.com/notifications/unsubscribe```
