### ISSUE TITLE
Some applications are not part of elementary

### ISSUE THREAD

**Issue by png2378** [bountysource/core#993]
Some applications are not part of [elementary](https://www.bountysource.com/teams/elementary) project. For example, this is [AppCenter](https://www.bountysource.com/trackers/179555-appcenter) and [Pantheon Mail](https://www.bountysource.com/trackers/26334537-pantheon-mail). Bouties for this apps are not shown on team's [main page](https://www.bountysource.com/teams/elementary), [issues](https://www.bountysource.com/teams/elementary/issues) page etc.

The current list of applications that are part of elementary project can be seen [here](https://launchpad.net/elementary).

**Comment by rappo** [comment]
Trackers and Teams that are included in a team's activity are up to the team's admin to decide, so I'm going to tag elementary OS's @danrabbit and close this issue. Daniel - if you run into any issues just ping me!
