### ISSUE TITLE
Salt: remove the 5$ threshold when make a one time donation.

### ISSUE THREAD

**Issue by tuxayo** [bountysource/core#996]
For donations from
- Bountysource credit
- Bitcoin

As they do not have a per transaction fee.

For Paypal maybe there could be a minimum 5$ charge. For a 1$ donation, 4$ will be kept in Bountysource credit. That would encourage to donate the remaining to other projects or to kept it for later.

**Comment by hjchan** [comment]
This is the current implementation, more details in https://github.com/bountysource/core/wiki/Salt-Frequently-Asked-Questions#is-there-a-minimum-contribution
